version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore(ci): "
    labels:
      - "ci-cd"
    assignees:
      - "apache/iggy-committers"
    reviewers:
      - "apache/iggy-committers"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore(deps): "
    assignees:
      - "apache/iggy-committers"
    reviewers:
      - "apache/iggy-committers"
