[profile.release]
lto = true
codegen-units = 1

[workspace]
resolver = "2"
members = [
    "bench",
    "cli",
    "cmd",
    "examples",
    "iggy",
    "integration",
    "server",
    "tools",
]
exclude = ["tpc"]
