[build.env]
passthrough = ["IGGY_SYSTEM_PATH"]

[target.aarch64-unknown-linux-gnu.env]
passthrough = ["QEMU_RUNNER=qemu-aarch64"]

[target.arm-unknown-linux-gnu.env]
passthrough = ["QEMU_RUNNER=qemu-arm"]
