[package]
name = "tpc"
version = "0.0.1"
edition = "2021"

[dependencies]
figlet-rs = "0.1.5"
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.18", features = ["fmt"] }
monoio = { version = "0.2.1", features = ["signal"] }

[[bin]]
name = "iggy-tpc"
path = "src/main.rs"
