// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

use std::{fmt::Write, sync::Arc};

use arrow::{
    array::{
        Array, BinaryArray, BooleanArray, Date32Array, Decimal128Array, Decimal256Array,
        Float64Array, Int32Array, Int64Array, RecordBatch, StringArray, TimestampMicrosecondArray,
    },
    datatypes::DataType,
};

use bytes::Bytes;
use futures::{StreamExt, pin_mut, stream};
use parquet::arrow::arrow_reader::ParquetRecordBatchReaderBuilder;
use pgwire::{
    api::results::{DataRowEncoder, FieldFormat, FieldInfo, QueryResponse, Response, Tag},
    error::{ErrorInfo, PgWireError, PgWireResult},
};

use s3::{Bucket, Region, creds::Credentials};
use sqlparser::ast::DataType as SDataType;
use sqlx::types::chrono;
use tokio_postgres::{
    Client as PgClient, GenericClient,
    binary_copy::BinaryCopyInWriter,
    types::{ToSql, Type as PgType},
};

use crate::connectors::fixtures::redshift::redshift_mock::{
    copy::{CopyFormat, RedshiftCopy},
    create::{RedshiftCreateTable, TableKind},
};

pub async fn execute_select(sql: &str, pg: &PgClient) -> PgWireResult<Response> {
    let value = pg
        .client()
        .query_one_scalar::<i32, _>(sql, &[])
        .await
        .map_err(|e| pg_wire_error(&e, "Query failed"))?;

    let schema = Arc::new(vec![FieldInfo::new(
        "column".into(),
        None,
        None,
        PgType::INT4,
        FieldFormat::Text,
    )]);

    let schema_ref = schema.clone();

    let row_stream = stream::iter(std::iter::once(value)).map(move |v| {
        let mut encoder = DataRowEncoder::new(schema_ref.clone());
        encoder.encode_field(&v)?;

        Ok(encoder.take_row())
    });

    Ok(Response::Query(QueryResponse::new(schema, row_stream)))
}

pub async fn execute_create_table(
    create: RedshiftCreateTable,
    pg: &PgClient,
) -> PgWireResult<Response> {
    let create_kw = match create.table_kind {
        TableKind::Regular => "CREATE TABLE",
        TableKind::Temp => "CREATE TEMP TABLE",
        // Postgres accepts (and ignores) the LOCAL keyword per the SQL
        // standard, so this round-trips fine.
        TableKind::LocalTemp => "CREATE LOCAL TEMPORARY TABLE",
    };

    let mut sql = String::from(create_kw);
    sql.push(' ');

    if create.if_not_exists {
        sql.push_str("IF NOT EXISTS ");
    }

    write!(sql, "{} (", create.table).unwrap();

    let fields = create.columns.iter().fold(vec![], |mut acc, v| {
        let mut f = format!("{} {}", v.name, map_type(&v.data_type));

        if let Some(id) = &v.identity {
            f.push_str(&format!(
                " GENERATED BY DEFAULT AS IDENTITY (START WITH {} INCREMENT BY {})",
                id.seed, id.step
            ));
        } else if let Some(default) = &v.default {
            let default = format!("{}", default).replace("GETDATE", "NOW");
            f.push_str(&format!(" DEFAULT {default}"));
        }

        if v.primary_key {
            f.push_str(" PRIMARY KEY");
        }

        if v.not_null {
            f.push_str(" NOT NULL");
        }

        if let Some(target) = &v.references {
            f.push_str(&format!(" REFERENCES {target}"));
        }

        acc.push(f);

        acc
    });

    sql.push_str(&fields.join(", "));
    sql.push_str(");");

    let rows_affected = pg
        .execute(&sql, &[])
        .await
        .map_err(|e| pg_wire_error(&e, "CREATE TABLE failed"))?;

    Ok(Response::Execution(
        Tag::new("create table").with_rows(rows_affected as usize),
    ))
}

pub async fn execute_s3_copy(
    copy: &RedshiftCopy,
    pg: &PgClient,
    s3_client: S3Client,
    bucket_name: &str,
    prefix: &str,
) -> PgWireResult<usize> {
    let table_name = copy.table.to_string();
    let mut failed_objects = 0usize;

    match &copy.format {
        CopyFormat::Parquet => {
            let existing_columns = fetch_table_columns(pg, &copy.table.to_string())
                .await
                .map_err(|e| e.to_pg_wire_error())?;

            tracing::info!(
                "target table '{table_name}' {}",
                if existing_columns.is_some() {
                    "exists"
                } else {
                    "does not exist"
                }
            );

            let bytes = Bytes::from(
                s3_client
                    .get_object(prefix)
                    .await
                    .map_err(|e| e.to_pg_wire_error())?,
            );

            tracing::info!("File '{}' read", prefix);

            let cols: Vec<ColumnDef> = match existing_columns {
                Some(cols) => strip_created_at(cols),
                None => {
                    let inferred =
                        infer_parquet_schema(bytes.clone()).map_err(|e| e.to_pg_wire_error())?;

                    let columns_sql = inferred
                        .iter()
                        .map(|f| format!("{} {}", f.name.to_lowercase(), f.pg_type.name()))
                        .collect::<Vec<_>>()
                        .join(", ");

                    create_table(pg, &table_name, &columns_sql)
                        .await
                        .map_err(|e| e.to_pg_wire_error())?;

                    strip_created_at(inferred)
                }
            };

            match load_one_object(pg, &copy.table.to_string(), &cols, bytes).await {
                Ok(n) => {
                    tracing::info!("{n} records stored");
                }
                Err(e) => {
                    // Simplification vs real Redshift: MAXERROR there counts bad *rows*
                    // across the whole load; here each failed *file* counts as one error.
                    // Good enough for a test double where you're usually asserting
                    // "load either fully succeeds or trips MAXERROR", not exact counts.
                    failed_objects += 1;
                    tracing::error!("[copy] error loading s3://{bucket_name}/{prefix}: {e:#}");
                    if failed_objects > copy.max_error as usize {
                        Err(format!("MAXERROR ({}) exceeded", copy.max_error).to_pg_wire_error())?
                    }
                }
            }
        }
        other => Err(format!("{:?} unsupported", other).to_pg_wire_error())?,
    };

    Ok(1)
}

async fn fetch_table_columns(pg: &PgClient, table: &str) -> Result<Option<Vec<ColumnDef>>, String> {
    let rows = pg
        .query(
            "SELECT column_name, udt_name FROM information_schema.columns \
         WHERE table_name = $1 ORDER BY ordinal_position",
            &[&table],
        )
        .await
        .map_err(|e| e.to_string())?;

    if rows.is_empty() {
        return Ok(None);
    }

    let rows: Result<Vec<ColumnDef>, String> = rows
        .into_iter()
        .map(|row| {
            let name: String = row.get(0);
            let udt: String = row.get(1);
            Ok(ColumnDef {
                name,
                pg_type: udt_name_to_type(&udt)?,
            })
        })
        .collect();

    Ok(Some(rows?))
}

async fn create_table(pg: &PgClient, table: &str, columns: &str) -> Result<usize, String> {
    let sql = format!("CREATE TABLE {} ({});", table, columns);

    tracing::info!("{sql}");

    let result = pg
        .client()
        .execute(&sql, &[])
        .await
        .map_err(|e| e.to_string())?;

    Ok(result as usize)
}

async fn load_one_object(
    pg: &PgClient,
    table: &str,
    columns: &[ColumnDef],
    bytes: Bytes,
) -> Result<usize, String> {
    let reader = ParquetRecordBatchReaderBuilder::try_new(bytes)
        .map_err(|e| e.to_string())?
        .build()
        .map_err(|e| e.to_string())?;

    let col_list = columns
        .iter()
        .map(|v| format!("\"{}\"", v.name))
        .collect::<Vec<String>>()
        .join(", ");

    let types = columns
        .iter()
        .map(|v| v.pg_type.clone())
        .collect::<Vec<PgType>>();

    let copy_sql = format!("COPY {table} ({col_list}) FROM STDIN BINARY");
    let sink = pg.copy_in(&copy_sql).await.map_err(|e| e.to_string())?;

    tracing::info!("COPY FROM STDIN started");

    let writer = BinaryCopyInWriter::new(sink, &types);

    pin_mut!(writer);

    let mut n = 0usize;

    for batch in reader {
        let batch = batch.map_err(|e| e.to_string())?;
        for row_idx in 0..batch.num_rows() {
            let row_values = extract_row(&batch, row_idx, columns)?;

            let refs: Vec<&(dyn ToSql + Sync)> = row_values
                .iter()
                .map(|v| v.as_ref() as &(dyn ToSql + Sync))
                .collect();

            writer
                .as_mut()
                .write(&refs)
                .await
                .map_err(|e| e.to_string())?;

            n += 1;
        }
    }

    writer.finish().await.map_err(|e| e.to_string())?;

    Ok(n)
}

struct ColumnDef {
    name: String,
    pg_type: PgType,
}

macro_rules! scalar_column {
    ($array:expr, $arr_ty:ty, $val_ty:ty, $row:expr, $conv:expr) => {{
        let a = $array
            .as_any()
            .downcast_ref::<$arr_ty>()
            .ok_or_else(|| format!("expected {} array", stringify!($arr_ty)))?;

        if a.is_null($row) {
            Box::new(None::<$val_ty>) as Box<dyn ToSql + Sync + Send>
        } else {
            let conv: fn(_) -> $val_ty = $conv;
            Box::new(conv(a.value($row))) as Box<dyn ToSql + Sync + Send>
        }
    }};
}

/// Only covers common scalar types. Extend as your Parquet exports need more —
/// this deliberately doesn't try to handle structs, lists, or decimals up front.
fn extract_row<'a>(
    batch: &'a RecordBatch,
    row: usize,
    columns: &'a [ColumnDef],
) -> Result<Vec<Box<dyn ToSql + Send + Sync + 'a>>, String> {
    let mut out = Vec::with_capacity(columns.len());

    for (i, col) in columns.iter().enumerate() {
        let array = batch.column(i);

        let value: Box<dyn ToSql + Sync + Send> = match array.data_type() {
            DataType::Utf8 => {
                scalar_column!(array, StringArray, String, row, |v: &str| v.to_string())
            }
            DataType::Int64 => {
                scalar_column!(array, Int64Array, i64, row, |v: i64| v)
            }
            DataType::Int32 => scalar_column!(array, Int32Array, i32, row, |v: i32| v),
            DataType::Float64 => scalar_column!(array, Float64Array, f64, row, |v: f64| v),
            DataType::Boolean => scalar_column!(array, BooleanArray, bool, row, |v: bool| v),
            DataType::Date32 => scalar_column!(array, Date32Array, i32, row, |v: i32| v),
            DataType::Binary => {
                scalar_column!(array, BinaryArray, Vec<u8>, row, |v: &[u8]| v.to_vec())
            }
            DataType::Decimal128(_, _) => {
                let a = array
                    .as_any()
                    .downcast_ref::<Decimal128Array>()
                    .ok_or("expected Decimal256Array")?;
                if a.is_null(row) {
                    Box::new(None::<String>)
                } else {
                    Box::new(a.value(row).to_string())
                }
            }
            // Downcast to fit i256 serialization constraints
            // Decimal(39, 0) > becomes Decimal256 on arrow
            // Decimal256 serialization will require extra handling
            DataType::Decimal256(_, _) => {
                let a = array
                    .as_any()
                    .downcast_ref::<Decimal256Array>()
                    .ok_or("expected Decimal256Array")?;
                if a.is_null(row) {
                    Box::new(None::<String>)
                } else {
                    let raw = a.value(row).to_string();
                    Box::new(raw)
                }
            }
            DataType::Timestamp(_, _) => {
                let a = array
                    .as_any()
                    .downcast_ref::<TimestampMicrosecondArray>()
                    .ok_or("expected TimestampMicrosecondArray")?;
                if a.is_null(row) {
                    Box::new(None::<chrono::DateTime<chrono::Utc>>)
                } else {
                    let micros = a.value(row);
                    let dt = chrono::DateTime::<chrono::Utc>::from_timestamp_micros(micros)
                        .ok_or("Invalid timestamp")?;
                    Box::new(dt)
                }
            }
            other => Err(format!(
                "unsupported parquet column type {other:?} for column {}",
                col.name
            ))?,
        };
        out.push(value);
    }

    Ok(out)
}

fn udt_name_to_type(udt: &str) -> Result<PgType, String> {
    Ok(match udt {
        "int2" => PgType::INT2,
        "int4" => PgType::INT4,
        "int8" => PgType::INT8,
        "float4" => PgType::FLOAT4,
        "float8" => PgType::FLOAT8,
        // Numeric serialiation requires extra work
        // Safe to use VARCHAR
        "numeric" => PgType::VARCHAR,
        "bool" => PgType::BOOL,
        "text" | "varchar" | "bpchar" => PgType::TEXT,
        "timestamp" => PgType::TIMESTAMP,
        "timestamptz" => PgType::TIMESTAMPTZ,
        "date" => PgType::DATE,
        "jsonb" => PgType::JSONB,
        "bytea" => PgType::BYTEA,
        other => Err(format!("unsupported column type for COPY target: {other}"))?,
    })
}

fn arrow_to_type(a_type: &DataType) -> Result<PgType, String> {
    match a_type {
        DataType::Boolean => Ok(PgType::BOOL),
        DataType::Binary | DataType::FixedSizeBinary(_) => Ok(PgType::BYTEA),
        DataType::Float64 => Ok(PgType::FLOAT8),
        DataType::Float32 | DataType::Float16 => Ok(PgType::FLOAT4),
        DataType::Int64 => Ok(PgType::INT8),
        DataType::Int32 => Ok(PgType::INT4),
        DataType::Decimal128(_, _) => Ok(PgType::VARCHAR),
        DataType::Decimal256(_, _) => Ok(PgType::VARCHAR),
        DataType::Utf8 => Ok(PgType::TEXT),
        DataType::Date32 => Ok(PgType::DATE),
        DataType::Timestamp(_, _) => Ok(PgType::TIMESTAMPTZ),
        other => Err(format!("Unsuppoerted type: {}", other)),
    }
}

fn map_type(dt: &SDataType) -> String {
    match dt {
        // Redshift's SUPER (semi-structured) has no PG equivalent for
        // your emulator's purposes -> JSON is the closest usable stand-in.
        SDataType::Custom(name, _) if name.to_string().eq_ignore_ascii_case("SUPER") => {
            "JSON".to_string()
        }
        SDataType::Custom(name, mods) if name.to_string().eq_ignore_ascii_case("VARBYTE") => {
            "BYTEA".to_string()
        }
        SDataType::Decimal(_) => "VARCHAR".into(),
        other => other.to_string(),
    }
}

fn infer_parquet_schema(bytes: Bytes) -> Result<Vec<ColumnDef>, String> {
    let reader = ParquetRecordBatchReaderBuilder::try_new(bytes).map_err(|e| e.to_string())?;

    reader
        .schema()
        .fields()
        .iter()
        .map(|v| {
            Ok(ColumnDef {
                name: v.name().into(),
                pg_type: arrow_to_type(v.data_type())?,
            })
        })
        .collect()
}

fn strip_created_at(cols: Vec<ColumnDef>) -> Vec<ColumnDef> {
    cols.into_iter()
        .filter(|v| v.name != "created_at")
        .collect()
}

/// S3
#[allow(unused)]
#[derive(Clone)]
pub struct S3Client {
    bucket_name: String,
    inner: Box<Bucket>,
}

impl S3Client {
    pub async fn new(
        bucket_name: &str,
        s3_endpoint: &str,
        access_key: &str,
        secret_key: &str,
        region: &str,
    ) -> Result<Self, String> {
        let region = Region::Custom {
            region: region.into(),
            endpoint: s3_endpoint.into(),
        };

        let credentials = Credentials::new(Some(access_key), Some(secret_key), None, None, None)
            .map_err(|e| e.to_string())?;

        let bucket = Bucket::new(bucket_name, region, credentials)
            .map_err(|e| format!("failed to setup bucket: {e}"))?
            .with_path_style();

        Ok(S3Client {
            bucket_name: bucket_name.into(),
            inner: bucket,
        })
    }

    pub async fn get_object(&self, key: &str) -> Result<Vec<u8>, String> {
        tracing::info!(
            "Downloading object '{}' from bucket '{}'",
            key,
            self.bucket_name
        );

        let response = self
            .inner
            .get_object(key)
            .await
            .map_err(|e| e.to_string())?;

        if response.status_code() != 200 {
            tracing::error!(
                "S3 get object returned status {}: {}",
                response.status_code(),
                String::from_utf8_lossy(response.as_slice())
            );
            return Err(format!(
                "S3 get_object failed with status {}",
                response.status_code()
            ));
        }

        tracing::info!(
            "Retrieved {} bytes to s3://{}/{}",
            response.bytes().len(),
            self.inner.name(),
            key
        );

        Ok(response.bytes().to_vec())
    }
}

pub fn split_s3_uri(uri: &str) -> Result<(String, String), String> {
    let rest = uri
        .strip_prefix("s3://")
        .ok_or("not an s3:// URI".to_string())?;

    match rest.split_once('/') {
        Some((b, p)) => Ok((b.to_string(), p.to_string())),
        None => Err(format!("s3 URI missing key/prefix: {uri}")),
    }
}

pub trait ToPgError {
    fn to_pg_wire_error(self) -> PgWireError;
}

impl<T> ToPgError for T
where
    T: Into<String>,
{
    fn to_pg_wire_error(self) -> PgWireError {
        PgWireError::UserError(Box::new(ErrorInfo::new(
            "ERROR".into(),
            "GG000".into(),
            self.into(),
        )))
    }
}

fn pg_wire_error(e: &tokio_postgres::Error, context: &str) -> PgWireError {
    match e.as_db_error() {
        Some(db_err) => PgWireError::UserError(Box::new(ErrorInfo::new(
            "ERROR".into(),
            db_err.code().code().to_string(),
            db_err.message().to_string(),
        ))),
        None => PgWireError::UserError(Box::new(ErrorInfo::new(
            "ERROR".into(),
            "XX000".into(),
            format!("{context}: {e}"),
        ))),
    }
}
