# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import asyncio
import builtins
import collections.abc
import datetime
import typing

__all__ = [
    "AutoCommit",
    "AutoCommitAfter",
    "AutoCommitWhen",
    "ConsumerGroup",
    "ConsumerGroupDetails",
    "ConsumerGroupMember",
    "IdentityInfo",
    "IggyClient",
    "IggyConsumer",
    "PollingStrategy",
    "ReceiveMessage",
    "SendMessage",
    "StreamDetails",
    "Topic",
    "TopicDetails",
]

class AutoCommit:
    r"""
    The auto-commit configuration for storing the offset on the server.

    Use this type with `IggyClient.consumer_group(..., auto_commit=...)`.
    """
    @typing.final
    class Disabled(AutoCommit):
        r"""
        Disable automatic offset commits. Offsets must be stored manually.
        """

        __match_args__ = ()
        def __new__(cls) -> AutoCommit.Disabled: ...
        def __len__(self) -> builtins.int: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...

    @typing.final
    class Interval(AutoCommit):
        r"""
        Commit offsets on a fixed interval.

        Args:
            interval: Interval between automatic offset commits as
                `datetime.timedelta`.
        """

        __match_args__ = ("interval",)
        @property
        def interval(self) -> datetime.timedelta: ...
        def __new__(cls, interval: datetime.timedelta) -> AutoCommit.Interval: ...

    @typing.final
    class IntervalOrWhen(AutoCommit):
        r"""
        Commit offsets on a fixed interval or according to an `AutoCommitWhen` mode.

        Args:
            interval: Interval between automatic offset commits as
                `datetime.timedelta`.
            when: Additional event that can trigger an offset commit as
                `AutoCommitWhen`.
        """

        __match_args__ = (
            "interval",
            "when",
        )
        @property
        def interval(self) -> datetime.timedelta: ...
        @property
        def when(self) -> AutoCommitWhen: ...
        def __new__(
            cls, interval: datetime.timedelta, when: AutoCommitWhen
        ) -> AutoCommit.IntervalOrWhen: ...

    @typing.final
    class IntervalOrAfter(AutoCommit):
        r"""
        Commit offsets on a fixed interval or according to an `AutoCommitAfter` mode.

        Args:
            interval: Interval between automatic offset commits as
                `datetime.timedelta`.
            after: Post-consumption condition that can also trigger an offset
                commit as `AutoCommitAfter`.
        """

        __match_args__ = (
            "interval",
            "after",
        )
        @property
        def interval(self) -> datetime.timedelta: ...
        @property
        def after(self) -> AutoCommitAfter: ...
        def __new__(
            cls, interval: datetime.timedelta, after: AutoCommitAfter
        ) -> AutoCommit.IntervalOrAfter: ...

    @typing.final
    class When(AutoCommit):
        r"""
        Commit offsets according to an `AutoCommitWhen` mode.

        Args:
            when: Event that triggers an offset commit as `AutoCommitWhen`.
        """

        __match_args__ = ("when",)
        @property
        def when(self) -> AutoCommitWhen: ...
        def __new__(cls, when: AutoCommitWhen) -> AutoCommit.When: ...

    @typing.final
    class After(AutoCommit):
        r"""
        Commit offsets according to an `AutoCommitAfter` mode.

        Args:
            after: Post-consumption condition that triggers an offset commit as
                `AutoCommitAfter`.
        """

        __match_args__ = ("after",)
        @property
        def after(self) -> AutoCommitAfter: ...
        def __new__(cls, after: AutoCommitAfter) -> AutoCommit.After: ...

    ...

class AutoCommitAfter:
    r"""
    The auto-commit mode for storing the offset on the server after receiving
    the messages.

    Use this type inside `AutoCommit.After(...)` or `AutoCommit.IntervalOrAfter(...)`.
    """
    @typing.final
    class ConsumingAllMessages(AutoCommitAfter):
        r"""
        Store the offset after all messages from a poll have been consumed.
        """

        __match_args__ = ()
        def __new__(cls) -> AutoCommitAfter.ConsumingAllMessages: ...
        def __len__(self) -> builtins.int: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...

    @typing.final
    class ConsumingEachMessage(AutoCommitAfter):
        r"""
        Store the offset after each consumed message.
        """

        __match_args__ = ()
        def __new__(cls) -> AutoCommitAfter.ConsumingEachMessage: ...
        def __len__(self) -> builtins.int: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...

    @typing.final
    class ConsumingEveryNthMessage(AutoCommitAfter):
        r"""
        Store the offset after every Nth consumed message.

        Args:
            count: Number of consumed messages between offset commits as `int`.
        """

        __match_args__ = ("count",)
        @property
        def count(self) -> builtins.int: ...
        def __new__(
            cls, count: builtins.int
        ) -> AutoCommitAfter.ConsumingEveryNthMessage: ...

    ...

class AutoCommitWhen:
    r"""
    The auto-commit mode for storing the offset on the server.

    Use this type inside `AutoCommit.When(...)` or `AutoCommit.IntervalOrWhen(...)`.
    """
    @typing.final
    class PollingMessages(AutoCommitWhen):
        r"""
        Store the offset when messages are polled from the server.
        """

        __match_args__ = ()
        def __new__(cls) -> AutoCommitWhen.PollingMessages: ...
        def __len__(self) -> builtins.int: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...

    @typing.final
    class ConsumingAllMessages(AutoCommitWhen):
        r"""
        Store the offset after all messages from a poll have been consumed.
        """

        __match_args__ = ()
        def __new__(cls) -> AutoCommitWhen.ConsumingAllMessages: ...
        def __len__(self) -> builtins.int: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...

    @typing.final
    class ConsumingEachMessage(AutoCommitWhen):
        r"""
        Store the offset after each consumed message.
        """

        __match_args__ = ()
        def __new__(cls) -> AutoCommitWhen.ConsumingEachMessage: ...
        def __len__(self) -> builtins.int: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...

    @typing.final
    class ConsumingEveryNthMessage(AutoCommitWhen):
        r"""
        Store the offset after every Nth consumed message.

        Args:
            count: Number of consumed messages between offset commits as `int`.
        """

        __match_args__ = ("count",)
        @property
        def count(self) -> builtins.int: ...
        def __new__(
            cls, count: builtins.int
        ) -> AutoCommitWhen.ConsumingEveryNthMessage: ...

    ...

@typing.final
class ConsumerGroup:
    @property
    def id(self) -> builtins.int:
        r"""
        Gets the unique identifier (numeric) of the consumer group.
        """
    @property
    def name(self) -> builtins.str:
        r"""
        Gets the name of the consumer group.
        """
    @property
    def partitions_count(self) -> builtins.int:
        r"""
        Gets the number of partitions the consumer group is consuming.
        """
    @property
    def members_count(self) -> builtins.int:
        r"""
        Gets the number of members in the consumer group.
        """

@typing.final
class ConsumerGroupDetails:
    @property
    def id(self) -> builtins.int:
        r"""
        Gets the unique identifier (numeric) of the consumer group.
        """
    @property
    def name(self) -> builtins.str:
        r"""
        Gets the name of the consumer group.
        """
    @property
    def partitions_count(self) -> builtins.int:
        r"""
        Gets the number of partitions the consumer group is consuming.
        """
    @property
    def members_count(self) -> builtins.int:
        r"""
        Gets the number of members in the consumer group.
        """
    @property
    def members(self) -> builtins.list[ConsumerGroupMember]:
        r"""
        Gets the collection of members in the consumer group.
        """

@typing.final
class ConsumerGroupMember:
    @property
    def id(self) -> builtins.int:
        r"""
        Gets the unique identifier (numeric) of the consumer group member.
        """
    @property
    def partitions_count(self) -> builtins.int:
        r"""
        Gets the number of partitions the consumer group member is consuming.
        """
    @property
    def partitions(self) -> builtins.list[builtins.int]:
        r"""
        Gets the collection of partitions the consumer group member is consuming.
        """

@typing.final
class IdentityInfo:
    r"""
    Authentication details returned by `IggyClient.login_user()`.

    This object contains the authenticated user id and any access token details
    returned by the server.
    """
    @property
    def user_id(self) -> builtins.int:
        r"""
        Get the authenticated user id.

        Returns:
            The user id as `int`.
        """
    @property
    def access_token_value(self) -> builtins.str | None:
        r"""
        Get the access token value.

        Returns:
            The access token as `str`, or `None` if no access token was returned.
        """
    @property
    def access_token_expiry(self) -> builtins.int | None:
        r"""
        Get the access token expiry value.

        Returns:
            The encoded expiry value as `int`, or `None` if no access token expiry
            was returned.
        """

@typing.final
class IggyClient:
    r"""
    A Python class representing the Iggy client.

    It wraps the RustIggyClient and provides asynchronous functionality
    through the contained runtime.

    Notes:
        Most request, transport, authentication, and server-side failures raise
        `PyRuntimeError`.
        Client-side validation failures that happen before a request is sent,
        such as invalid `str | int` identifiers, raise `PyValueError`.
        Async message iterators created through consumers end iteration with
        `StopAsyncIteration`.
    """
    def __new__(
        cls,
        *,
        server_address: builtins.str | None = None,
        reconnection_max_retries: builtins.int | None = None,
        reconnection_interval: datetime.timedelta | None = None,
        reestablish_after: datetime.timedelta | None = None,
        tls_enabled: builtins.bool | None = None,
        tls_domain: builtins.str | None = None,
        tls_ca_file: builtins.str | None = None,
        tls_validate_certificate: builtins.bool | None = None,
        no_delay: builtins.bool = False,
    ) -> IggyClient:
        r"""
        Create an `IggyClient`.

        Use this constructor when you want to configure the connection with
        explicit keyword arguments instead of a connection string.

        Args:
            server_address: Server address as `str` in `host:port` form. Pass `None`
                to use the TCP transport default, currently `127.0.0.1:8090`.
            reconnection_max_retries: Maximum number of reconnect attempts as `int`
                after a disconnect. Pass `None` to use the TCP transport default,
                currently unlimited retries.
            reconnection_interval: Delay between reconnect attempts as
                `datetime.timedelta`. Pass `None` to use the TCP transport default,
                currently 1 second.
            reestablish_after: Delay before attempting to reestablish the
                connection as `datetime.timedelta`. Pass `None` to use the TCP
                transport default, currently 5 seconds.
            tls_enabled: Whether to use TLS for the connection as `bool`. Pass
                `None` to use the TCP transport default, currently `False`.
            tls_domain: Server name as `str` to validate against the TLS certificate.
                Pass `None` to use the TCP transport default, currently an empty
                string that triggers auto-detection from `server_address`. This
                option is ignored when `tls_enabled` is `False`.
            tls_ca_file: Path as `str` to a CA certificate file used to validate
                the server certificate. Pass `None` to use the TCP transport
                default, currently no CA file. This option is ignored when
                `tls_enabled` is `False`.
            tls_validate_certificate: Whether to validate the server certificate.
                Accepts `bool | None`. Pass `None` to use the TCP transport
                default, currently `True`. This option is ignored when
                `tls_enabled` is `False`.
            no_delay: Whether to send packets immediately instead of allowing the
                socket to coalesce small writes. Accepts `bool`. Defaults to
                `False`.

        Returns:
            A configured `IggyClient`.

        Raises:
            PyRuntimeError: If the connection settings are invalid.
        """
    @classmethod
    def from_connection_string(cls, connection_string: builtins.str) -> IggyClient:
        r"""
        Create an `IggyClient` from a connection string.

        Use this when the connection configuration is already available as a single string.

        Args:
            connection_string: Connection string as `str` describing how to connect
                to the server.

        Returns:
            A configured `IggyClient`.

        Raises:
            PyRuntimeError: If the connection string is invalid.
        """
    def ping(self) -> collections.abc.Awaitable[None]:
        r"""
        Check whether the server is reachable.

        Sends a ping request and waits for the server to respond.

        Returns:
            An awaitable that resolves to `None` when the server responds.

        Raises:
            PyRuntimeError: If the request fails or the server cannot be reached.
        """
    def login_user(
        self, username: builtins.str, password: builtins.str
    ) -> collections.abc.Awaitable[IdentityInfo]:
        r"""
        Authenticate with a username and password.

        Args:
            username: Username as `str`.
            password: Password as `str`.

        Returns:
            An awaitable that resolves to `IdentityInfo` for the authenticated user.

        Raises:
            PyRuntimeError: If authentication fails or the request cannot be completed.
        """
    def connect(self) -> collections.abc.Awaitable[None]:
        r"""
        Open the connection to the server.

        Returns:
            An awaitable that resolves to `None` when the connection is established.

        Raises:
            PyRuntimeError: If the connection attempt fails.
        """
    def create_stream(
        self, name: builtins.str
    ) -> collections.abc.Awaitable[StreamDetails]:
        r"""
        Create a stream.

        Args:
            name: Stream name as `str`.

        Returns:
            An awaitable that resolves to `StreamDetails` for the created stream.

        Raises:
            PyRuntimeError: If the stream cannot be created.
        """
    def get_stream(
        self, stream_id: builtins.str | builtins.int
    ) -> collections.abc.Awaitable[StreamDetails | None]:
        r"""
        Get a stream by identifier.

        Args:
            stream_id: Stream identifier as `str | int`.

        Returns:
            An awaitable that resolves to `StreamDetails` if the stream exists,
            or `None` if it does not.

        Raises:
            PyValueError: If the identifier is invalid.
            PyRuntimeError: If the request fails.
        """
    def create_topic(
        self,
        stream: builtins.str | builtins.int,
        name: builtins.str,
        partitions_count: builtins.int,
        compression_algorithm: builtins.str | None = None,
        replication_factor: builtins.int | None = None,
        message_expiry: datetime.timedelta | None = None,
        max_topic_size: builtins.int | None = None,
    ) -> collections.abc.Awaitable[TopicDetails]:
        r"""
        Create a topic in a stream.

        Args:
            stream: Stream identifier as `str | int`.
            name: Topic name as `str`.
            partitions_count: Number of partitions to create as `int`.
            compression_algorithm: Compression algorithm as `str | None`. Supported
                values are `\"none\"` and `\"gzip\"`, case-insensitive. If `None`,
                the default compression setting is used.
            replication_factor: Replication factor as `int | None` from `0` to `255`.
                Passing `0` or `None` uses the server default. The current server
                default is `1`.
            message_expiry: Message retention period as `datetime.timedelta | None`.
                Use `datetime.timedelta(0)` to request the server default, which
                currently means messages do not expire. If `None`, the server default
                is also used.
            max_topic_size: Maximum topic size in bytes as `int | None`. Use `0` to request the
                server default, which is currently unlimited. If `None`, the server
                default is also used.

        Returns:
            An awaitable that resolves to `TopicDetails` for the created topic.

        Raises:
            PyValueError: If the stream identifier is invalid.
            PyRuntimeError: If another argument is invalid or the topic cannot be
                created.
        """
    def get_topic(
        self,
        stream_id: builtins.str | builtins.int,
        topic_id: builtins.str | builtins.int,
    ) -> collections.abc.Awaitable[TopicDetails | None]:
        r"""
        Get a topic by stream and topic identifier.

        Args:
            stream_id: Stream identifier as `str | int`.
            topic_id: Topic identifier as `str | int`.

        Returns:
            An awaitable that resolves to `TopicDetails` if the topic exists,
            or `None` if it does not.

        Raises:
            PyValueError: If a stream or topic identifier is invalid.
            PyRuntimeError: If the request fails.
        """
    def get_topics(
        self, stream_id: builtins.str | builtins.int
    ) -> collections.abc.Awaitable[list[Topic]]:
        r"""
        Get all topics in a stream.

        Args:
            stream_id: Stream identifier as `str | int`.

        Returns:
            An awaitable that resolves to `list[Topic]`.

        Raises:
            PyValueError: If the stream identifier is invalid.
            PyRuntimeError: If the request fails.
        """
    def update_topic(
        self,
        stream_id: builtins.str | builtins.int,
        topic_id: builtins.str | builtins.int,
        name: builtins.str,
        compression_algorithm: builtins.str | None = None,
        replication_factor: builtins.int | None = None,
        message_expiry: datetime.timedelta | None = None,
        max_topic_size: builtins.int | None = None,
    ) -> collections.abc.Awaitable[None]:
        r"""
        Update an existing topic.

        This is a full replacement: any optional parameter left unset is reset to
        its server default rather than preserved.

        Args:
            stream_id: Stream identifier as `str | int`.
            topic_id: Topic identifier as `str | int`.
            name: New topic name as `str`.
            compression_algorithm: Compression algorithm as `str | None`.
            replication_factor: Replication factor as `int | None`.
            message_expiry: Message expiry as `datetime.timedelta | None`.
            max_topic_size: Maximum topic size in bytes as `int | None`.

        Returns:
            An awaitable that resolves to `None` when the topic is updated.

        Raises:
            PyValueError: If a stream or topic identifier is invalid.
            PyRuntimeError: If another argument is invalid or the request fails.
        """
    def delete_topic(
        self,
        stream_id: builtins.str | builtins.int,
        topic_id: builtins.str | builtins.int,
    ) -> collections.abc.Awaitable[None]:
        r"""
        Delete a topic from a stream.

        Args:
            stream_id: Stream identifier as `str | int`.
            topic_id: Topic identifier as `str | int`.

        Returns:
            An awaitable that resolves to `None` when the topic is deleted.

        Raises:
            PyValueError: If a stream or topic identifier is invalid.
            PyRuntimeError: If the request fails.
        """
    def purge_topic(
        self,
        stream_id: builtins.str | builtins.int,
        topic_id: builtins.str | builtins.int,
    ) -> collections.abc.Awaitable[None]:
        r"""
        Purge all messages from a topic.

        Args:
            stream_id: Stream identifier as `str | int`.
            topic_id: Topic identifier as `str | int`.

        Returns:
            An awaitable that resolves to `None` when the topic is purged.

        Raises:
            PyValueError: If a stream or topic identifier is invalid.
            PyRuntimeError: If the request fails.
        """
    def create_consumer_group(
        self,
        stream_id: builtins.str | builtins.int,
        topic_id: builtins.str | builtins.int,
        name: builtins.str,
    ) -> collections.abc.Awaitable[None]:
        r"""
        Create a consumer group for a stream and topic.

        Args:
            stream_id: Stream identifier as `str | int`.
            topic_id: Topic identifier as `str | int`.
            name: Consumer group name as `str`.

        Returns:
            An awaitable that resolves to `None` when the consumer group is created.

        Raises:
            PyValueError: If an identifier is invalid.
            PyRuntimeError: If the request fails.
        """
    def get_consumer_group(
        self,
        stream_id: builtins.str | builtins.int,
        topic_id: builtins.str | builtins.int,
        group_id: builtins.str | builtins.int,
    ) -> collections.abc.Awaitable[ConsumerGroupDetails | None]:
        r"""
        Retrieve details for a consumer group from the specified stream and topic.

        Args:
            stream_id: Stream identifier as `str | int`.
            topic_id: Topic identifier as `str | int`.
            group_id: Consumer group identifier as `str | int`.

        Returns:
            An awaitable that resolves to `ConsumerGroupDetails` if the consumer group exists,
            or `None` otherwise.

        Raises:
            PyValueError: If an identifier is invalid.
            PyRuntimeError: If the request fails.
        """
    def get_consumer_groups(
        self,
        stream_id: builtins.str | builtins.int,
        topic_id: builtins.str | builtins.int,
    ) -> collections.abc.Awaitable[list[ConsumerGroup]]:
        r"""
        Get all consumer groups for the specified stream and topic.

        Args:
            stream_id: Stream identifier as `str | int`.
            topic_id: Topic identifier as `str | int`.

        Returns:
            An awaitable that resolves to `list[ConsumerGroup]`.

        Raises:
            PyValueError: If an identifier is invalid.
            PyRuntimeError: If the request fails.
        """
    def send_messages(
        self,
        stream: builtins.str | builtins.int,
        topic: builtins.str | builtins.int,
        partitioning: builtins.int,
        messages: list[SendMessage],
    ) -> collections.abc.Awaitable[None]:
        r"""
        Send messages to a topic partition.

        Args:
            stream: Stream identifier as `str | int`.
            topic: Topic identifier as `str | int`.
            partitioning: Partition id as `int`.
            messages: Messages to publish as `list[SendMessage]`.

        Returns:
            An awaitable that resolves to `None` after the messages are sent.

        Raises:
            PyValueError: If a stream or topic identifier is invalid, or if a
                message payload fails client-side validation.
            PyRuntimeError: If the send request fails.
        """
    def poll_messages(
        self,
        stream: builtins.str | builtins.int,
        topic: builtins.str | builtins.int,
        partition_id: builtins.int,
        polling_strategy: PollingStrategy,
        count: builtins.int,
        auto_commit: builtins.bool,
    ) -> collections.abc.Awaitable[list[ReceiveMessage]]:
        r"""
        Poll messages from a topic partition.

        Args:
            stream: Stream identifier as `str | int`.
            topic: Topic identifier as `str | int`.
            partition_id: Partition to read from as `int`.
            polling_strategy: Polling strategy as `PollingStrategy`. See
                `PollingStrategy` for the available variants and their payloads.
            count: Maximum number of messages to return as `int`.
            auto_commit: Whether to store the consumer offset automatically after
                polling as `bool`.

        Returns:
            An awaitable that resolves to a `list[ReceiveMessage]`.

        Raises:
            PyValueError: If a stream or topic identifier is invalid.
            PyRuntimeError: If the poll request fails.
        """
    def consumer_group(
        self,
        name: builtins.str,
        stream: builtins.str,
        topic: builtins.str,
        partition_id: builtins.int | None = None,
        polling_strategy: PollingStrategy | None = None,
        batch_length: builtins.int | None = None,
        auto_commit: AutoCommit | None = None,
        create_consumer_group_if_not_exists: builtins.bool = True,
        auto_join_consumer_group: builtins.bool = True,
        poll_interval: datetime.timedelta | None = None,
        polling_retry_interval: datetime.timedelta | None = None,
        init_retries: builtins.int | None = None,
        init_retry_interval: datetime.timedelta | None = None,
        allow_replay: builtins.bool = False,
    ) -> collections.abc.Awaitable[IggyConsumer]:
        r"""
        Create a consumer group consumer.

        Args:
            name: Consumer group name as `str`.
            stream: Stream identifier as `str`.
            topic: Topic identifier as `str`.
            partition_id: Partition id as `int | None`. If `None`, partition
                assignment is left to the consumer group.
            polling_strategy: Polling strategy as `PollingStrategy | None`. See
                `PollingStrategy` for the available variants and their payloads.
                If `None`, reading starts from the next message after the stored offset.
            batch_length: Maximum number of messages to fetch per poll as `int | None`.
                If `None`, the default is `1000`.
            auto_commit: Offset commit policy as `AutoCommit | None`. See
                `AutoCommit` for the available modes. If `None`, offsets are committed
                every second and when messages are polled.
            create_consumer_group_if_not_exists: Whether to create the consumer
                group automatically if it does not exist as `bool`. Defaults to `True`.
            auto_join_consumer_group: Whether to join the consumer group automatically
                during initialization as `bool`. Defaults to `True`.
            poll_interval: Delay between polling attempts as `datetime.timedelta | None`.
                If `None`, no poll interval is configured.
            polling_retry_interval: Delay before retrying polling after a disconnect
                as `datetime.timedelta | None`. If `None`, the default is 1 second.
            init_retries: Number of retries to use during initialization when the
                stream or topic is not available as `int | None`. If `None`,
                initialization is not retried.
            init_retry_interval: Delay between initialization retries as
                `datetime.timedelta | None`. Must be set together with `init_retries`.
            allow_replay: Whether replaying previously available messages is allowed.
                Accepts `bool`. Defaults to `False`.

        Returns:
            An awaitable that resolves to `IggyConsumer`.

        Raises:
            PyRuntimeError: If the configuration is invalid or the consumer cannot
                be initialized.
        """

@typing.final
class IggyConsumer:
    r"""
    A Python class representing the Iggy consumer.

    It wraps the RustIggyConsumer and provides asynchronous functionality
    through the contained runtime.

    Notes:
        Consumer operations raise `PyRuntimeError` for runtime failures such as
        polling, offset storage, callback execution, or shutdown errors.
        Async iteration ends with `StopAsyncIteration` from
        `ReceiveMessageIterator.__anext__()` when no more messages are available.
    """
    def get_last_consumed_offset(
        self, partition_id: builtins.int
    ) -> builtins.int | None:
        r"""
        Get the last consumed offset for a partition.

        Args:
            partition_id: Partition id as `int`.

        Returns:
            The last consumed offset as `int`, or `None` if no offset has been consumed yet.
        """
    def get_last_stored_offset(self, partition_id: builtins.int) -> builtins.int | None:
        r"""
        Get the last stored offset for a partition.

        Args:
            partition_id: Partition id as `int`.

        Returns:
            The last stored offset as `int`, or `None` if no offset has been stored yet.
        """
    def name(self) -> builtins.str:
        r"""
        Get the consumer group name.

        Returns:
            The consumer group name as `str`.
        """
    def partition_id(self) -> builtins.int:
        r"""
        Get the current partition id.

        Returns:
            The current partition id as `int`. Returns `0` if no messages have been
            polled yet.
        """
    def stream(self) -> builtins.str | builtins.int:
        r"""
        Get the configured stream identifier.

        Returns:
            The stream identifier as `str | int`, depending on how the consumer was configured.

        Raises:
            PyRuntimeError: If the identifier cannot be converted for Python.
        """
    def topic(self) -> builtins.str | builtins.int:
        r"""
        Get the configured topic identifier.

        Returns:
            The topic identifier as `str | int`, depending on how the consumer was configured.

        Raises:
            PyRuntimeError: If the identifier cannot be converted for Python.
        """
    def store_offset(
        self, offset: builtins.int, partition_id: builtins.int | None
    ) -> collections.abc.Awaitable[None]:
        r"""
        Store a consumer offset on the server.

        Args:
            offset: Offset to store as `int`.
            partition_id: Partition id as `int | None`. If `None`, the current
                consumer partition is used.

        Returns:
            An awaitable that resolves to `None` when the offset is stored.

        Raises:
            PyRuntimeError: If storing the offset fails.
        """
    def delete_offset(
        self, partition_id: builtins.int | None
    ) -> collections.abc.Awaitable[None]:
        r"""
        Delete a stored consumer offset from the server.

        Args:
            partition_id: Partition id as `int | None`. If `None`, the current
                consumer partition is used.

        Returns:
            An awaitable that resolves to `None` when the offset is deleted.

        Raises:
            PyRuntimeError: If deleting the offset fails.
        """
    def iter_messages(self) -> collections.abc.AsyncIterator[ReceiveMessage]:
        r"""
        Create an async iterator over `ReceiveMessage`.

        Returns:
            A `collections.abc.AsyncIterator[ReceiveMessage]`.

        Raises:
            PyRuntimeError: If polling messages fails while iterating.
            StopAsyncIteration: From `ReceiveMessageIterator.__anext__()` when the
                iterator is exhausted.

        Notes:
            This method does not currently support `AutoCommit.After`.
            For `AutoCommit.IntervalOrAfter(datetime.timedelta, AutoCommitAfter)`,
            only the interval part is applied; the `after` mode is ignored.
            Use `consume_messages()` if you need commit-after-processing semantics.
        """
    def consume_messages(
        self,
        callback: collections.abc.Callable[
            [ReceiveMessage], collections.abc.Awaitable[None]
        ],
        shutdown_event: asyncio.Event | None,
    ) -> collections.abc.Awaitable[None]:
        r"""
        Consume messages continuously with an async callback.

        Args:
            callback: Async callback as
                `collections.abc.Callable[[ReceiveMessage], collections.abc.Awaitable[None]]`.
                It is called once for each `ReceiveMessage`.
            shutdown_event: Optional `asyncio.Event`. If provided, consumption
                stops when the event is set.

        Returns:
            An awaitable that resolves to `None` when consumption stops.

        Raises:
            PyRuntimeError: If message consumption fails or shutdown signaling fails.
        """

class PollingStrategy:
    r"""
    The starting point used when polling messages.

    Use this type with `IggyClient.poll_messages(..., polling_strategy=...)` and
    `IggyClient.consumer_group(..., polling_strategy=...)`.
    """
    @typing.final
    class Offset(PollingStrategy):
        r"""
        Start reading from an absolute offset.

        Args:
            value: Absolute message offset as `int`.
        """

        __match_args__ = ("value",)
        @property
        def value(self) -> builtins.int: ...
        def __new__(cls, value: builtins.int) -> PollingStrategy.Offset: ...

    @typing.final
    class Timestamp(PollingStrategy):
        r"""
        Start reading from the first message at or after a timestamp.

        Args:
            value: Unix timestamp in microseconds as `int`.
        """

        __match_args__ = ("value",)
        @property
        def value(self) -> builtins.int: ...
        def __new__(cls, value: builtins.int) -> PollingStrategy.Timestamp: ...

    @typing.final
    class First(PollingStrategy):
        r"""
        Start reading from the first available message.
        """

        __match_args__ = ()
        def __new__(cls) -> PollingStrategy.First: ...

    @typing.final
    class Last(PollingStrategy):
        r"""
        Start reading from the most recent available message.
        """

        __match_args__ = ()
        def __new__(cls) -> PollingStrategy.Last: ...

    @typing.final
    class Next(PollingStrategy):
        r"""
        Start reading from the next message after the stored consumer offset.
        """

        __match_args__ = ()
        def __new__(cls) -> PollingStrategy.Next: ...

    ...

@typing.final
class ReceiveMessage:
    r"""
    A message returned by `IggyClient.poll_messages()` or `IggyConsumer`.

    This object exposes the payload and metadata for a single received message.
    """
    @property
    def payload(self) -> bytes:
        r"""
        Get the message payload.

        Returns:
            The payload as `bytes`.
        """
    @property
    def offset(self) -> builtins.int:
        r"""
        Get the message offset.

        Returns:
            The message offset as `int`.
        """
    @property
    def timestamp(self) -> builtins.int:
        r"""
        Get the message timestamp.

        Returns:
            The message timestamp as `int`.
        """
    @property
    def id(self) -> builtins.int:
        r"""
        Get the message id.

        Returns:
            The message id as `int`.
        """
    @property
    def checksum(self) -> builtins.int:
        r"""
        Get the message checksum.

        Returns:
            The checksum as `int`.
        """
    @property
    def length(self) -> builtins.int:
        r"""
        Get the payload length.

        Returns:
            The payload length in bytes as `int`.
        """
    @property
    def partition_id(self) -> builtins.int:
        r"""
        Get the partition id for this message.

        Returns:
            The partition id as `int`.
        """

@typing.final
class SendMessage:
    r"""
    A message to publish with `IggyClient.send_messages()`.
    """
    def __new__(cls, data: builtins.str | bytes) -> SendMessage:
        r"""
        Create a `SendMessage`.

        Args:
            data: Message payload as `str | bytes`.

        Returns:
            A `SendMessage`.

        Raises:
            PyValueError: If the payload cannot be converted into a message.
        """

@typing.final
class StreamDetails:
    r"""
    Metadata returned for a stream.

    This object is returned by `IggyClient.create_stream()` and
    `IggyClient.get_stream()`.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Get the stream id.

        Returns:
            The stream id as `int`.
        """
    @property
    def name(self) -> builtins.str:
        r"""
        Get the stream name.

        Returns:
            The stream name as `str`.
        """
    @property
    def created_at(self) -> builtins.int:
        r"""
        Get the stream creation timestamp.

        Returns:
            The creation timestamp in microseconds since the Unix epoch as `int`.
        """
    @property
    def size(self) -> builtins.int:
        r"""
        Get the stream size in bytes.

        Returns:
            The total stream size in bytes as `int`.
        """
    @property
    def messages_count(self) -> builtins.int:
        r"""
        Get the number of messages in the stream.

        Returns:
            The message count as `int`.
        """
    @property
    def topics_count(self) -> builtins.int:
        r"""
        Get the number of topics in the stream.

        Returns:
            The topic count as `int`.
        """

@typing.final
class Topic:
    @property
    def id(self) -> builtins.int:
        r"""
        The unique identifier (numeric) of the topic.
        """
    @property
    def name(self) -> builtins.str:
        r"""
        The unique name of the topic.
        """
    @property
    def messages_count(self) -> builtins.int:
        r"""
        The total number of messages in the topic.
        """
    @property
    def partitions_count(self) -> builtins.int:
        r"""
        The total number of partitions in the topic.
        """

@typing.final
class TopicDetails:
    @property
    def id(self) -> builtins.int:
        r"""
        The unique identifier (numeric) of the topic.
        """
    @property
    def name(self) -> builtins.str:
        r"""
        The unique name of the topic.
        """
    @property
    def messages_count(self) -> builtins.int:
        r"""
        The total number of messages in the topic.
        """
    @property
    def partitions_count(self) -> builtins.int:
        r"""
        The total number of partitions in the topic.
        """
    @property
    def compression_algorithm(self) -> builtins.str:
        r"""
        Compression algorithm for the topic.
        """
    @property
    def replication_factor(self) -> builtins.int:
        r"""
        Replication factor for the topic.
        """
