/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.3/samples
 */

plugins {
    java
    id("com.diffplug.spotless") version "8.1.0"
    checkstyle
}

dependencies {
    implementation("org.apache.iggy:iggy:0.6.0-SNAPSHOT")
    implementation("org.slf4j:slf4j-simple:2.0.13")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.20.1")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.20.1")
}

repositories {
      mavenCentral()
      maven { url = uri("https://repository.apache.org/content/repositories/snapshots/") }
}

spotless {
    java {
        palantirJavaFormat()
        removeUnusedImports()
        trimTrailingWhitespace()
        endWithNewline()
        formatAnnotations()
        importOrder("", "\n", "javax|java", "\n", "\\#")
        toggleOffOn() 
    }
}

checkstyle {
    toolVersion = "12.2.0"
}

tasks.withType<JavaCompile> {
    dependsOn("spotlessApply")
}

tasks.register<JavaExec>("runGettingStartedProducer") {
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("org.apache.iggy.examples.gettingstarted.producer.GettingStartedProducer")
}
tasks.register<JavaExec>("runGettingStartedConsumer") {
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("org.apache.iggy.examples.gettingstarted.consumer.GettingStartedConsumer")
}
tasks.register<JavaExec>("runBasicProducer") {
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("org.apache.iggy.examples.basic.producer.BasicProducer")
}
tasks.register<JavaExec>("runBasicConsumer") {
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("org.apache.iggy.examples.basic.consumer.BasicConsumer")
}
tasks.register<JavaExec>("runMessageHeadersProducer") {
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("org.apache.iggy.examples.messageheaders.producer.MessageHeadersProducer")
}