[package]
name = "server"
version = "0.0.45"
edition = "2021"
build = "src/build.rs"

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.70"
async-trait = "0.1.68"
axum = "0.6.20"
axum-server = { version = "0.5.1", features = ["tls-rustls", "tokio-rustls"] }
bcrypt = "0.15.0"
blake3 = "1.5.0"
byte-unit = "4.0.19"
bytes = "1.4.0"
chrono = "0.4.30"
clap = { version = "4.1.11", features = ["derive"] }
figlet-rs = "0.1.5"
figment = { version = "0.10.8", features = ["json", "toml", "env"] }
flume = "0.11.0"
futures = "0.3.28"
iggy = { path = "../iggy" }
jsonwebtoken = "9.0.0"
prometheus-client = "0.21.2"
quinn = "0.10.0"
rcgen = "0.11.1"
ring = "0.17.0"
rmp-serde = "1.1.2"
rustls = { version = "0.21.1", features = ["dangerous_configuration", "quic"] }
rustls-pemfile = "1.0.3"
serde = { version = "1.0.159", features = ["derive", "rc"] }
serde_json = "1.0.95"
serde_with = { version = "3.0.0", features = ["base64"] }
sled = "0.34.7"
strip-ansi-escapes = "0.2.0"
sysinfo = "0.29.5"
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["full"] }
tokio-graceful-shutdown = "0.13.0"
tokio-native-tls = "0.3.1"
tokio-rustls = "0.24.0"
toml = "0.8.0"
tower = { version = "0.4.13" }
tower-http = { version = "0.4.0", features = [
    "add-extension",
    "cors",
    "trace",
] }
tower-layer = "0.3.2"
tower-service = "0.3.2"
tracing = { version = "0.1.37" }
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.17", features = ["fmt"] }
uuid = { version = "1.3.3", features = ["v4", "fast-rng", "zerocopy"] }
xxhash-rust = { version = "0.8.2", features = ["xxh32"] }

[dev-dependencies]
assert_cmd = "2.0.12"
libc = "0.2.147"
predicates = "3.0.3"
serial_test = "2.0.0"

[build-dependencies]
vergen = { version = "8.2.4", features = [
    "build",
    "cargo",
    "git",
    "gitcl",
    "rustc",
] }

[[bin]]
name = "iggy-server"
path = "src/main.rs"
