[package]
name = "server"
version = "0.1.7"
edition = "2021"
build = "src/build.rs"

[features]
default = []
jemalloc = ["dep:tikv-jemallocator"]

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.79"
async-trait = "0.1.77"
atone = "0.3.7"
axum = "0.7.3"
axum-server = { version = "0.6.0", features = ["tls-rustls"] }
bcrypt = "0.15.0"
blake3 = "1.5.0"
byte-unit = { version = "5.1.2", default-features = false, features = [
    "serde",
    "byte",
] }
bytes = "1.5.0"
chrono = "0.4.31"
clap = { version = "4.4.13", features = ["derive"] }
dashmap = "5.5.3"
figlet-rs = "0.1.5"
figment = { version = "0.10.13", features = ["json", "toml", "env"] }
flume = "0.11.0"
futures = "0.3.30"
iggy = { path = "../iggy" }
jsonwebtoken = "9.2.0"
keepcalm = "0.3.5"
moka = { version = "0.12.3", features = ["future"] }
prometheus-client = "0.22.0"
quinn = { version = "0.10.2" }
rcgen = "0.12.0"
ring = "0.17.7"
rmp-serde = "1.1.2"
rustls = { version = "0.21.10" }
rustls-pemfile = "2.0.0"
serde = { version = "1.0.194", features = ["derive", "rc"] }
serde_json = "1.0.111"
serde_with = { version = "3.3.0", features = ["base64", "macros"] }
sled = "0.34.7"
strip-ansi-escapes = "0.2.0"
sysinfo = "0.30.5"
thiserror = "1.0.56"
tokio = { version = "1.33.0", features = ["full"] }
tokio-native-tls = "0.3.1"
toml = "0.8.8"
tower = { version = "0.4.13" }
tower-http = { version = "0.5.0", features = [
    "add-extension",
    "cors",
    "trace",
] }
tower-layer = "0.3.2"
tower-service = "0.3.2"
tracing = { version = "0.1.40" }
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18", features = ["fmt"] }
ulid = "1.1.0"
uuid = { version = "1.6.1", features = ["v4", "fast-rng", "zerocopy"] }
xxhash-rust = { version = "0.8.8", features = ["xxh32"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.5", optional = true }

[build-dependencies]
vergen = { version = "8.2.6", features = [
    "build",
    "cargo",
    "git",
    "gitcl",
    "rustc",
] }

[[bin]]
name = "iggy-server"
path = "src/main.rs"
