[package]
name = "server"
version = "0.2.2"
edition = "2021"
build = "src/build.rs"

[features]
default = []
jemalloc = ["dep:tikv-jemallocator"]
tokio-console = ["dep:console-subscriber", "tokio/tracing"]

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.79"
async-trait = "0.1.77"
atone = "0.3.7"
axum = "0.7.4"
axum-server = { version = "0.6.0", features = ["tls-rustls"] }
bcrypt = "0.15.0"
blake3 = "1.5.0"
byte-unit = { version = "5.1.4", default-features = false, features = [
    "serde",
    "byte",
] }
bytes = "1.5.0"
chrono = "0.4.33"
clap = { version = "4.5.1", features = ["derive"] }
console-subscriber = { version = "0.2.0", optional = true }
dashmap = "5.5.3"
figlet-rs = "0.1.5"
figment = { version = "0.10.14", features = ["json", "toml", "env"] }
flume = "0.11.0"
futures = "0.3.30"
iggy = { path = "../sdk" }
jsonwebtoken = "9.2.0"
keepcalm = "0.3.5"
moka = { version = "0.12.5", features = ["future"] }
prometheus-client = "0.22.1"
quinn = { version = "0.10.2" }
rcgen = "0.12.1"
ring = "0.17.7"
rmp-serde = "1.1.2"
rustls = { version = "0.21.10" }
rustls-pemfile = "2.1.0"
serde = { version = "1.0.196", features = ["derive", "rc"] }
serde_json = "1.0.113"
serde_with = { version = "3.6.1", features = ["base64", "macros"] }
sled = "0.34.7"
strip-ansi-escapes = "0.2.0"
sysinfo = "0.30.5"
thiserror = "1.0.57"
tokio = { version = "1.36.0", features = ["full"] }
tokio-native-tls = "0.3.1"
toml = "0.8.10"
tower = { version = "0.4.13" }
tower-http = { version = "0.5.1", features = [
    "add-extension",
    "cors",
    "trace",
] }
tower-layer = "0.3.2"
tower-service = "0.3.2"
tracing = { version = "0.1.40" }
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18", features = ["fmt"] }
ulid = "1.1.2"
uuid = { version = "1.7.0", features = ["v4", "fast-rng", "zerocopy"] }
xxhash-rust = { version = "0.8.8", features = ["xxh32"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.5", optional = true }

[build-dependencies]
vergen = { version = "8.3.1", features = [
    "build",
    "cargo",
    "git",
    "gitcl",
    "rustc",
] }

[[bin]]
name = "iggy-server"
path = "src/main.rs"

# This is a workaround for cargo-udeps to ignore these dependencies
# in case if feature 'tokio-console' is enabled.
[package.metadata.cargo-udeps.ignore]
normal = ["tracing-appender", "strip-ansi-escapes"]
