// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package ierror

import (
	"errors"
	"fmt"
	"testing"
)

func TestFromCode_ReturnsCorrectErrors(t *testing.T) {
	tests := []struct {
		name string
		code Code
		err  IggyError
	}{
		{"Error", ErrorCode, ErrError},
		{"InvalidConfiguration", InvalidConfigurationCode, ErrInvalidConfiguration},
		{"InvalidCommand", InvalidCommandCode, ErrInvalidCommand},
		{"InvalidFormat", InvalidFormatCode, ErrInvalidFormat},
		{"FeatureUnavailable", FeatureUnavailableCode, ErrFeatureUnavailable},
		{"InvalidIdentifier", InvalidIdentifierCode, ErrInvalidIdentifier},
		{"InvalidVersion", InvalidVersionCode, ErrInvalidVersion},
		{"Disconnected", DisconnectedCode, ErrDisconnected},
		{"CannotEstablishConnection", CannotEstablishConnectionCode, ErrCannotEstablishConnection},
		{"CannotCreateBaseDirectory", CannotCreateBaseDirectoryCode, ErrCannotCreateBaseDirectory},
		{"CannotCreateRuntimeDirectory", CannotCreateRuntimeDirectoryCode, ErrCannotCreateRuntimeDirectory},
		{"CannotRemoveRuntimeDirectory", CannotRemoveRuntimeDirectoryCode, ErrCannotRemoveRuntimeDirectory},
		{"CannotCreateStateDirectory", CannotCreateStateDirectoryCode, ErrCannotCreateStateDirectory},
		{"StateFileNotFound", StateFileNotFoundCode, ErrStateFileNotFound},
		{"StateFileCorrupted", StateFileCorruptedCode, ErrStateFileCorrupted},
		{"InvalidStateEntryChecksum", InvalidStateEntryChecksumCode, ErrInvalidStateEntryChecksum},
		{"CannotOpenDatabase", CannotOpenDatabaseCode, ErrCannotOpenDatabase},
		{"ResourceNotFound", ResourceNotFoundCode, ErrResourceNotFound},
		{"StaleClient", StaleClientCode, ErrStaleClient},
		{"TcpError", TcpErrorCode, ErrTcpError},
		{"QuicError", QuicErrorCode, ErrQuicError},
		{"InvalidServerAddress", InvalidServerAddressCode, ErrInvalidServerAddress},
		{"InvalidClientAddress", InvalidClientAddressCode, ErrInvalidClientAddress},
		{"InvalidIpAddress", InvalidIpAddressCode, ErrInvalidIpAddress},
		{"Unauthenticated", UnauthenticatedCode, ErrUnauthenticated},
		{"Unauthorized", UnauthorizedCode, ErrUnauthorized},
		{"InvalidCredentials", InvalidCredentialsCode, ErrInvalidCredentials},
		{"InvalidUsername", InvalidUsernameCode, ErrInvalidUsername},
		{"InvalidPassword", InvalidPasswordCode, ErrInvalidPassword},
		{"InvalidUserStatus", InvalidUserStatusCode, ErrInvalidUserStatus},
		{"UserAlreadyExists", UserAlreadyExistsCode, ErrUserAlreadyExists},
		{"UserInactive", UserInactiveCode, ErrUserInactive},
		{"CannotDeleteUser", CannotDeleteUserCode, ErrCannotDeleteUser},
		{"CannotChangePermissions", CannotChangePermissionsCode, ErrCannotChangePermissions},
		{"InvalidPersonalAccessTokenName", InvalidPersonalAccessTokenNameCode, ErrInvalidPersonalAccessTokenName},
		{"PersonalAccessTokenAlreadyExists", PersonalAccessTokenAlreadyExistsCode, ErrPersonalAccessTokenAlreadyExists},
		{"PersonalAccessTokensLimitReached", PersonalAccessTokensLimitReachedCode, ErrPersonalAccessTokensLimitReached},
		{"InvalidPersonalAccessToken", InvalidPersonalAccessTokenCode, ErrInvalidPersonalAccessToken},
		{"PersonalAccessTokenExpired", PersonalAccessTokenExpiredCode, ErrPersonalAccessTokenExpired},
		{"UsersLimitReached", UsersLimitReachedCode, ErrUsersLimitReached},
		{"NotConnected", NotConnectedCode, ErrNotConnected},
		{"ClientShutdown", ClientShutdownCode, ErrClientShutdown},
		{"InvalidTlsDomain", InvalidTlsDomainCode, ErrInvalidTlsDomain},
		{"InvalidTlsCertificatePath", InvalidTlsCertificatePathCode, ErrInvalidTlsCertificatePath},
		{"InvalidTlsCertificate", InvalidTlsCertificateCode, ErrInvalidTlsCertificate},
		{"FailedToAddCertificate", FailedToAddCertificateCode, ErrFailedToAddCertificate},
		{"InvalidEncryptionKey", InvalidEncryptionKeyCode, ErrInvalidEncryptionKey},
		{"CannotEncryptData", CannotEncryptDataCode, ErrCannotEncryptData},
		{"CannotDecryptData", CannotDecryptDataCode, ErrCannotDecryptData},
		{"InvalidJwtAlgorithm", InvalidJwtAlgorithmCode, ErrInvalidJwtAlgorithm},
		{"InvalidJwtSecret", InvalidJwtSecretCode, ErrInvalidJwtSecret},
		{"JwtMissing", JwtMissingCode, ErrJwtMissing},
		{"CannotGenerateJwt", CannotGenerateJwtCode, ErrCannotGenerateJwt},
		{"AccessTokenMissing", AccessTokenMissingCode, ErrAccessTokenMissing},
		{"InvalidAccessToken", InvalidAccessTokenCode, ErrInvalidAccessToken},
		{"InvalidSizeBytes", InvalidSizeBytesCode, ErrInvalidSizeBytes},
		{"InvalidUtf8", InvalidUtf8Code, ErrInvalidUtf8},
		{"InvalidNumberEncoding", InvalidNumberEncodingCode, ErrInvalidNumberEncoding},
		{"InvalidBooleanValue", InvalidBooleanValueCode, ErrInvalidBooleanValue},
		{"InvalidNumberValue", InvalidNumberValueCode, ErrInvalidNumberValue},
		{"ClientNotFound", ClientNotFoundCode, ErrClientNotFound},
		{"InvalidClientId", InvalidClientIdCode, ErrInvalidClientId},
		{"ConnectionClosed", ConnectionClosedCode, ErrConnectionClosed},
		{"CannotParseHeaderKind", CannotParseHeaderKindCode, ErrCannotParseHeaderKind},
		{"HttpResponseError", HttpResponseErrorCode, ErrHttpResponseError},
		{"InvalidHttpRequest", InvalidHttpRequestCode, ErrInvalidHttpRequest},
		{"InvalidJsonResponse", InvalidJsonResponseCode, ErrInvalidJsonResponse},
		{"InvalidBytesResponse", InvalidBytesResponseCode, ErrInvalidBytesResponse},
		{"EmptyResponse", EmptyResponseCode, ErrEmptyResponse},
		{"CannotCreateEndpoint", CannotCreateEndpointCode, ErrCannotCreateEndpoint},
		{"CannotParseUrl", CannotParseUrlCode, ErrCannotParseUrl},
		{"CannotCreateStreamsDirectory", CannotCreateStreamsDirectoryCode, ErrCannotCreateStreamsDirectory},
		{"CannotCreateStreamDirectory", CannotCreateStreamDirectoryCode, ErrCannotCreateStreamDirectory},
		{"CannotCreateStreamInfo", CannotCreateStreamInfoCode, ErrCannotCreateStreamInfo},
		{"CannotUpdateStreamInfo", CannotUpdateStreamInfoCode, ErrCannotUpdateStreamInfo},
		{"CannotOpenStreamInfo", CannotOpenStreamInfoCode, ErrCannotOpenStreamInfo},
		{"CannotReadStreamInfo", CannotReadStreamInfoCode, ErrCannotReadStreamInfo},
		{"CannotCreateStream", CannotCreateStreamCode, ErrCannotCreateStream},
		{"CannotDeleteStream", CannotDeleteStreamCode, ErrCannotDeleteStream},
		{"CannotDeleteStreamDirectory", CannotDeleteStreamDirectoryCode, ErrCannotDeleteStreamDirectory},
		{"StreamIdNotFound", StreamIdNotFoundCode, ErrStreamIdNotFound},
		{"StreamNameNotFound", StreamNameNotFoundCode, ErrStreamNameNotFound},
		{"StreamIdAlreadyExists", StreamIdAlreadyExistsCode, ErrStreamIdAlreadyExists},
		{"StreamNameAlreadyExists", StreamNameAlreadyExistsCode, ErrStreamNameAlreadyExists},
		{"InvalidStreamName", InvalidStreamNameCode, ErrInvalidStreamName},
		{"InvalidStreamId", InvalidStreamIdCode, ErrInvalidStreamId},
		{"CannotReadStreams", CannotReadStreamsCode, ErrCannotReadStreams},
		{"InvalidTopicSize", InvalidTopicSizeCode, ErrInvalidTopicSize},
		{"CannotCreateTopicsDirectory", CannotCreateTopicsDirectoryCode, ErrCannotCreateTopicsDirectory},
		{"CannotCreateTopicDirectory", CannotCreateTopicDirectoryCode, ErrCannotCreateTopicDirectory},
		{"CannotCreateTopicInfo", CannotCreateTopicInfoCode, ErrCannotCreateTopicInfo},
		{"CannotUpdateTopicInfo", CannotUpdateTopicInfoCode, ErrCannotUpdateTopicInfo},
		{"CannotOpenTopicInfo", CannotOpenTopicInfoCode, ErrCannotOpenTopicInfo},
		{"CannotReadTopicInfo", CannotReadTopicInfoCode, ErrCannotReadTopicInfo},
		{"CannotCreateTopic", CannotCreateTopicCode, ErrCannotCreateTopic},
		{"CannotDeleteTopic", CannotDeleteTopicCode, ErrCannotDeleteTopic},
		{"CannotDeleteTopicDirectory", CannotDeleteTopicDirectoryCode, ErrCannotDeleteTopicDirectory},
		{"CannotPollTopic", CannotPollTopicCode, ErrCannotPollTopic},
		{"TopicIdNotFound", TopicIdNotFoundCode, ErrTopicIdNotFound},
		{"TopicNameNotFound", TopicNameNotFoundCode, ErrTopicNameNotFound},
		{"TopicIdAlreadyExists", TopicIdAlreadyExistsCode, ErrTopicIdAlreadyExists},
		{"TopicNameAlreadyExists", TopicNameAlreadyExistsCode, ErrTopicNameAlreadyExists},
		{"InvalidTopicName", InvalidTopicNameCode, ErrInvalidTopicName},
		{"TooManyPartitions", TooManyPartitionsCode, ErrTooManyPartitions},
		{"InvalidTopicId", InvalidTopicIdCode, ErrInvalidTopicId},
		{"CannotReadTopics", CannotReadTopicsCode, ErrCannotReadTopics},
		{"InvalidReplicationFactor", InvalidReplicationFactorCode, ErrInvalidReplicationFactor},
		{"CannotCreatePartition", CannotCreatePartitionCode, ErrCannotCreatePartition},
		{"CannotCreatePartitionsDirectory", CannotCreatePartitionsDirectoryCode, ErrCannotCreatePartitionsDirectory},
		{"CannotCreatePartitionDirectory", CannotCreatePartitionDirectoryCode, ErrCannotCreatePartitionDirectory},
		{"CannotOpenPartitionLogFile", CannotOpenPartitionLogFileCode, ErrCannotOpenPartitionLogFile},
		{"CannotReadPartitions", CannotReadPartitionsCode, ErrCannotReadPartitions},
		{"CannotDeletePartition", CannotDeletePartitionCode, ErrCannotDeletePartition},
		{"CannotDeletePartitionDirectory", CannotDeletePartitionDirectoryCode, ErrCannotDeletePartitionDirectory},
		{"PartitionNotFound", PartitionNotFoundCode, ErrPartitionNotFound},
		{"NoPartitions", NoPartitionsCode, ErrNoPartitions},
		{"TopicFull", TopicFullCode, ErrTopicFull},
		{"CannotDeleteConsumerOffsetsDirectory", CannotDeleteConsumerOffsetsDirectoryCode, ErrCannotDeleteConsumerOffsetsDirectory},
		{"CannotDeleteConsumerOffsetFile", CannotDeleteConsumerOffsetFileCode, ErrCannotDeleteConsumerOffsetFile},
		{"CannotCreateConsumerOffsetsDirectory", CannotCreateConsumerOffsetsDirectoryCode, ErrCannotCreateConsumerOffsetsDirectory},
		{"CannotReadConsumerOffsets", CannotReadConsumerOffsetsCode, ErrCannotReadConsumerOffsets},
		{"ConsumerOffsetNotFound", ConsumerOffsetNotFoundCode, ErrConsumerOffsetNotFound},
		{"SegmentNotFound", SegmentNotFoundCode, ErrSegmentNotFound},
		{"SegmentClosed", SegmentClosedCode, ErrSegmentClosed},
		{"InvalidSegmentSize", InvalidSegmentSizeCode, ErrInvalidSegmentSize},
		{"CannotCreateSegmentLogFile", CannotCreateSegmentLogFileCode, ErrCannotCreateSegmentLogFile},
		{"CannotCreateSegmentIndexFile", CannotCreateSegmentIndexFileCode, ErrCannotCreateSegmentIndexFile},
		{"CannotCreateSegmentTimeIndexFile", CannotCreateSegmentTimeIndexFileCode, ErrCannotCreateSegmentTimeIndexFile},
		{"CannotSaveMessagesToSegment", CannotSaveMessagesToSegmentCode, ErrCannotSaveMessagesToSegment},
		{"CannotSaveIndexToSegment", CannotSaveIndexToSegmentCode, ErrCannotSaveIndexToSegment},
		{"CannotSaveTimeIndexToSegment", CannotSaveTimeIndexToSegmentCode, ErrCannotSaveTimeIndexToSegment},
		{"InvalidMessagesCount", InvalidMessagesCountCode, ErrInvalidMessagesCount},
		{"CannotAppendMessage", CannotAppendMessageCode, ErrCannotAppendMessage},
		{"CannotReadMessage", CannotReadMessageCode, ErrCannotReadMessage},
		{"CannotReadMessageId", CannotReadMessageIdCode, ErrCannotReadMessageId},
		{"CannotReadMessageState", CannotReadMessageStateCode, ErrCannotReadMessageState},
		{"CannotReadMessageTimestamp", CannotReadMessageTimestampCode, ErrCannotReadMessageTimestamp},
		{"CannotReadHeadersLength", CannotReadHeadersLengthCode, ErrCannotReadHeadersLength},
		{"CannotReadHeadersPayload", CannotReadHeadersPayloadCode, ErrCannotReadHeadersPayload},
		{"TooBigUserHeaders", TooBigUserHeadersCode, ErrTooBigUserHeaders},
		{"InvalidHeaderKey", InvalidHeaderKeyCode, ErrInvalidHeaderKey},
		{"InvalidHeaderValue", InvalidHeaderValueCode, ErrInvalidHeaderValue},
		{"CannotReadMessageLength", CannotReadMessageLengthCode, ErrCannotReadMessageLength},
		{"CannotReadMessagePayload", CannotReadMessagePayloadCode, ErrCannotReadMessagePayload},
		{"TooBigMessagePayload", TooBigMessagePayloadCode, ErrTooBigMessagePayload},
		{"TooManyMessages", TooManyMessagesCode, ErrTooManyMessages},
		{"EmptyMessagePayload", EmptyMessagePayloadCode, ErrEmptyMessagePayload},
		{"InvalidMessagePayloadLength", InvalidMessagePayloadLengthCode, ErrInvalidMessagePayloadLength},
		{"CannotReadMessageChecksum", CannotReadMessageChecksumCode, ErrCannotReadMessageChecksum},
		{"InvalidMessageChecksum", InvalidMessageChecksumCode, ErrInvalidMessageChecksum},
		{"InvalidKeyValueLength", InvalidKeyValueLengthCode, ErrInvalidKeyValueLength},
		{"CommandLengthError", CommandLengthErrorCode, ErrCommandLengthError},
		{"InvalidSegmentsCount", InvalidSegmentsCountCode, ErrInvalidSegmentsCount},
		{"NonZeroOffset", NonZeroOffsetCode, ErrNonZeroOffset},
		{"NonZeroTimestamp", NonZeroTimestampCode, ErrNonZeroTimestamp},
		{"MissingIndex", MissingIndexCode, ErrMissingIndex},
		{"InvalidIndexesByteSize", InvalidIndexesByteSizeCode, ErrInvalidIndexesByteSize},
		{"InvalidIndexesCount", InvalidIndexesCountCode, ErrInvalidIndexesCount},
		{"InvalidMessagesSize", InvalidMessagesSizeCode, ErrInvalidMessagesSize},
		{"TooSmallMessage", TooSmallMessageCode, ErrTooSmallMessage},
		{"CannotSendMessagesDueToClientDisconnection", CannotSendMessagesDueToClientDisconnectionCode, ErrCannotSendMessagesDueToClientDisconnection},
		{"BackgroundSendError", BackgroundSendErrorCode, ErrBackgroundSendError},
		{"BackgroundSendTimeout", BackgroundSendTimeoutCode, ErrBackgroundSendTimeout},
		{"BackgroundSendBufferFull", BackgroundSendBufferFullCode, ErrBackgroundSendBufferFull},
		{"BackgroundWorkerDisconnected", BackgroundWorkerDisconnectedCode, ErrBackgroundWorkerDisconnected},
		{"BackgroundSendBufferOverflow", BackgroundSendBufferOverflowCode, ErrBackgroundSendBufferOverflow},
		{"ProducerSendFailed", ProducerSendFailedCode, ErrProducerSendFailed},
		{"ProducerClosed", ProducerClosedCode, ErrProducerClosed},
		{"InvalidOffset", InvalidOffsetCode, ErrInvalidOffset},
		{"ConsumerGroupIdNotFound", ConsumerGroupIdNotFoundCode, ErrConsumerGroupIdNotFound},
		{"ConsumerGroupIdAlreadyExists", ConsumerGroupIdAlreadyExistsCode, ErrConsumerGroupIdAlreadyExists},
		{"InvalidConsumerGroupId", InvalidConsumerGroupIdCode, ErrInvalidConsumerGroupId},
		{"ConsumerGroupNameNotFound", ConsumerGroupNameNotFoundCode, ErrConsumerGroupNameNotFound},
		{"ConsumerGroupNameAlreadyExists", ConsumerGroupNameAlreadyExistsCode, ErrConsumerGroupNameAlreadyExists},
		{"InvalidConsumerGroupName", InvalidConsumerGroupNameCode, ErrInvalidConsumerGroupName},
		{"ConsumerGroupMemberNotFound", ConsumerGroupMemberNotFoundCode, ErrConsumerGroupMemberNotFound},
		{"CannotCreateConsumerGroupInfo", CannotCreateConsumerGroupInfoCode, ErrCannotCreateConsumerGroupInfo},
		{"CannotDeleteConsumerGroupInfo", CannotDeleteConsumerGroupInfoCode, ErrCannotDeleteConsumerGroupInfo},
		{"MissingBaseOffsetRetainedMessageBatch", MissingBaseOffsetRetainedMessageBatchCode, ErrMissingBaseOffsetRetainedMessageBatch},
		{"MissingLastOffsetDeltaRetainedMessageBatch", MissingLastOffsetDeltaRetainedMessageBatchCode, ErrMissingLastOffsetDeltaRetainedMessageBatch},
		{"MissingMaxTimestampRetainedMessageBatch", MissingMaxTimestampRetainedMessageBatchCode, ErrMissingMaxTimestampRetainedMessageBatch},
		{"MissingLengthRetainedMessageBatch", MissingLengthRetainedMessageBatchCode, ErrMissingLengthRetainedMessageBatch},
		{"MissingPayloadRetainedMessageBatch", MissingPayloadRetainedMessageBatchCode, ErrMissingPayloadRetainedMessageBatch},
		{"CannotReadBatchBaseOffset", CannotReadBatchBaseOffsetCode, ErrCannotReadBatchBaseOffset},
		{"CannotReadBatchLength", CannotReadBatchLengthCode, ErrCannotReadBatchLength},
		{"CannotReadLastOffsetDelta", CannotReadLastOffsetDeltaCode, ErrCannotReadLastOffsetDelta},
		{"CannotReadMaxTimestamp", CannotReadMaxTimestampCode, ErrCannotReadMaxTimestamp},
		{"CannotReadBatchPayload", CannotReadBatchPayloadCode, ErrCannotReadBatchPayload},
		{"InvalidConnectionString", InvalidConnectionStringCode, ErrInvalidConnectionString},
		{"SnapshotFileCompletionFailed", SnapshotFileCompletionFailedCode, ErrSnapshotFileCompletionFailed},
		{"CannotSerializeResource", CannotSerializeResourceCode, ErrCannotSerializeResource},
		{"CannotDeserializeResource", CannotDeserializeResourceCode, ErrCannotDeserializeResource},
		{"CannotReadFile", CannotReadFileCode, ErrCannotReadFile},
		{"CannotReadFileMetadata", CannotReadFileMetadataCode, ErrCannotReadFileMetadata},
		{"CannotSeekFile", CannotSeekFileCode, ErrCannotSeekFile},
		{"CannotAppendToFile", CannotAppendToFileCode, ErrCannotAppendToFile},
		{"CannotWriteToFile", CannotWriteToFileCode, ErrCannotWriteToFile},
		{"CannotOverwriteFile", CannotOverwriteFileCode, ErrCannotOverwriteFile},
		{"CannotDeleteFile", CannotDeleteFileCode, ErrCannotDeleteFile},
		{"CannotSyncFile", CannotSyncFileCode, ErrCannotSyncFile},
		{"CannotReadIndexOffset", CannotReadIndexOffsetCode, ErrCannotReadIndexOffset},
		{"CannotReadIndexPosition", CannotReadIndexPositionCode, ErrCannotReadIndexPosition},
		{"CannotReadIndexTimestamp", CannotReadIndexTimestampCode, ErrCannotReadIndexTimestamp},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := FromCode(tt.code)
			if got == nil {
				t.Fatalf("FromCode(%d) returned nil", tt.code)
			}
			if got.Code() != tt.code {
				t.Fatalf("FromCode(%d).Code() = %d, want %d", tt.code, got.Code(), tt.code)
			}
			if got.Error() == "" {
				t.Fatalf("FromCode(%d).Error() returned empty string", tt.code)
			}
			if !errors.Is(got, tt.err) {
				t.Fatalf("errors.Is(FromCode(%d), expected) = false, want true", tt.code)
			}
		})
	}
}

func TestFromCode_UnknownCode(t *testing.T) {
	got := FromCode(Code(99999))
	if got == nil {
		t.Fatalf("FromCode(99999) returned nil, expected fallback error")
	}
	if got.Code() != ErrorCode {
		t.Fatalf("FromCode(99999).Code() = %d, want %d (fallback to ErrError)", got.Code(), ErrorCode)
	}
}

func TestCodeString_AllCodes(t *testing.T) {
	allCodes := []Code{
		ErrorCode,
		InvalidConfigurationCode,
		InvalidCommandCode,
		InvalidFormatCode,
		FeatureUnavailableCode,
		InvalidIdentifierCode,
		InvalidVersionCode,
		DisconnectedCode,
		CannotEstablishConnectionCode,
		CannotCreateBaseDirectoryCode,
		CannotCreateRuntimeDirectoryCode,
		CannotRemoveRuntimeDirectoryCode,
		CannotCreateStateDirectoryCode,
		StateFileNotFoundCode,
		StateFileCorruptedCode,
		InvalidStateEntryChecksumCode,
		CannotOpenDatabaseCode,
		ResourceNotFoundCode,
		StaleClientCode,
		TcpErrorCode,
		QuicErrorCode,
		InvalidServerAddressCode,
		InvalidClientAddressCode,
		InvalidIpAddressCode,
		UnauthenticatedCode,
		UnauthorizedCode,
		InvalidCredentialsCode,
		InvalidUsernameCode,
		InvalidPasswordCode,
		InvalidUserStatusCode,
		UserAlreadyExistsCode,
		UserInactiveCode,
		CannotDeleteUserCode,
		CannotChangePermissionsCode,
		InvalidPersonalAccessTokenNameCode,
		PersonalAccessTokenAlreadyExistsCode,
		PersonalAccessTokensLimitReachedCode,
		InvalidPersonalAccessTokenCode,
		PersonalAccessTokenExpiredCode,
		UsersLimitReachedCode,
		NotConnectedCode,
		ClientShutdownCode,
		InvalidTlsDomainCode,
		InvalidTlsCertificatePathCode,
		InvalidTlsCertificateCode,
		FailedToAddCertificateCode,
		InvalidEncryptionKeyCode,
		CannotEncryptDataCode,
		CannotDecryptDataCode,
		InvalidJwtAlgorithmCode,
		InvalidJwtSecretCode,
		JwtMissingCode,
		CannotGenerateJwtCode,
		AccessTokenMissingCode,
		InvalidAccessTokenCode,
		InvalidSizeBytesCode,
		InvalidUtf8Code,
		InvalidNumberEncodingCode,
		InvalidBooleanValueCode,
		InvalidNumberValueCode,
		ClientNotFoundCode,
		InvalidClientIdCode,
		ConnectionClosedCode,
		CannotParseHeaderKindCode,
		HttpResponseErrorCode,
		InvalidHttpRequestCode,
		InvalidJsonResponseCode,
		InvalidBytesResponseCode,
		EmptyResponseCode,
		CannotCreateEndpointCode,
		CannotParseUrlCode,
		CannotCreateStreamsDirectoryCode,
		CannotCreateStreamDirectoryCode,
		CannotCreateStreamInfoCode,
		CannotUpdateStreamInfoCode,
		CannotOpenStreamInfoCode,
		CannotReadStreamInfoCode,
		CannotCreateStreamCode,
		CannotDeleteStreamCode,
		CannotDeleteStreamDirectoryCode,
		StreamIdNotFoundCode,
		StreamNameNotFoundCode,
		StreamIdAlreadyExistsCode,
		StreamNameAlreadyExistsCode,
		InvalidStreamNameCode,
		InvalidStreamIdCode,
		CannotReadStreamsCode,
		InvalidTopicSizeCode,
		CannotCreateTopicsDirectoryCode,
		CannotCreateTopicDirectoryCode,
		CannotCreateTopicInfoCode,
		CannotUpdateTopicInfoCode,
		CannotOpenTopicInfoCode,
		CannotReadTopicInfoCode,
		CannotCreateTopicCode,
		CannotDeleteTopicCode,
		CannotDeleteTopicDirectoryCode,
		CannotPollTopicCode,
		TopicIdNotFoundCode,
		TopicNameNotFoundCode,
		TopicIdAlreadyExistsCode,
		TopicNameAlreadyExistsCode,
		InvalidTopicNameCode,
		TooManyPartitionsCode,
		InvalidTopicIdCode,
		CannotReadTopicsCode,
		InvalidReplicationFactorCode,
		CannotCreatePartitionCode,
		CannotCreatePartitionsDirectoryCode,
		CannotCreatePartitionDirectoryCode,
		CannotOpenPartitionLogFileCode,
		CannotReadPartitionsCode,
		CannotDeletePartitionCode,
		CannotDeletePartitionDirectoryCode,
		PartitionNotFoundCode,
		NoPartitionsCode,
		TopicFullCode,
		CannotDeleteConsumerOffsetsDirectoryCode,
		CannotDeleteConsumerOffsetFileCode,
		CannotCreateConsumerOffsetsDirectoryCode,
		CannotReadConsumerOffsetsCode,
		ConsumerOffsetNotFoundCode,
		SegmentNotFoundCode,
		SegmentClosedCode,
		InvalidSegmentSizeCode,
		CannotCreateSegmentLogFileCode,
		CannotCreateSegmentIndexFileCode,
		CannotCreateSegmentTimeIndexFileCode,
		CannotSaveMessagesToSegmentCode,
		CannotSaveIndexToSegmentCode,
		CannotSaveTimeIndexToSegmentCode,
		InvalidMessagesCountCode,
		CannotAppendMessageCode,
		CannotReadMessageCode,
		CannotReadMessageIdCode,
		CannotReadMessageStateCode,
		CannotReadMessageTimestampCode,
		CannotReadHeadersLengthCode,
		CannotReadHeadersPayloadCode,
		TooBigUserHeadersCode,
		InvalidHeaderKeyCode,
		InvalidHeaderValueCode,
		CannotReadMessageLengthCode,
		CannotReadMessagePayloadCode,
		TooBigMessagePayloadCode,
		TooManyMessagesCode,
		EmptyMessagePayloadCode,
		InvalidMessagePayloadLengthCode,
		CannotReadMessageChecksumCode,
		InvalidMessageChecksumCode,
		InvalidKeyValueLengthCode,
		CommandLengthErrorCode,
		InvalidSegmentsCountCode,
		NonZeroOffsetCode,
		NonZeroTimestampCode,
		MissingIndexCode,
		InvalidIndexesByteSizeCode,
		InvalidIndexesCountCode,
		InvalidMessagesSizeCode,
		TooSmallMessageCode,
		CannotSendMessagesDueToClientDisconnectionCode,
		BackgroundSendErrorCode,
		BackgroundSendTimeoutCode,
		BackgroundSendBufferFullCode,
		BackgroundWorkerDisconnectedCode,
		BackgroundSendBufferOverflowCode,
		ProducerSendFailedCode,
		ProducerClosedCode,
		InvalidOffsetCode,
		ConsumerGroupIdNotFoundCode,
		ConsumerGroupIdAlreadyExistsCode,
		InvalidConsumerGroupIdCode,
		ConsumerGroupNameNotFoundCode,
		ConsumerGroupNameAlreadyExistsCode,
		InvalidConsumerGroupNameCode,
		ConsumerGroupMemberNotFoundCode,
		CannotCreateConsumerGroupInfoCode,
		CannotDeleteConsumerGroupInfoCode,
		MissingBaseOffsetRetainedMessageBatchCode,
		MissingLastOffsetDeltaRetainedMessageBatchCode,
		MissingMaxTimestampRetainedMessageBatchCode,
		MissingLengthRetainedMessageBatchCode,
		MissingPayloadRetainedMessageBatchCode,
		CannotReadBatchBaseOffsetCode,
		CannotReadBatchLengthCode,
		CannotReadLastOffsetDeltaCode,
		CannotReadMaxTimestampCode,
		CannotReadBatchPayloadCode,
		InvalidConnectionStringCode,
		SnapshotFileCompletionFailedCode,
		CannotSerializeResourceCode,
		CannotDeserializeResourceCode,
		CannotReadFileCode,
		CannotReadFileMetadataCode,
		CannotSeekFileCode,
		CannotAppendToFileCode,
		CannotWriteToFileCode,
		CannotOverwriteFileCode,
		CannotDeleteFileCode,
		CannotSyncFileCode,
		CannotReadIndexOffsetCode,
		CannotReadIndexPositionCode,
		CannotReadIndexTimestampCode,
	}

	for _, code := range allCodes {
		s := code.String()
		if s == "" {
			t.Fatalf("Code(%d).String() returned empty string", code)
		}
		if s == "Unknown error code" {
			t.Fatalf("Code(%d).String() returned %q, expected a known name", code, s)
		}
	}
}

func TestCodeString_UnknownCode(t *testing.T) {
	s := Code(99999).String()
	if s != "Unknown error code" {
		t.Fatalf("Code(99999).String() = %q, want %q", s, "Unknown error code")
	}
}

func TestErrorsIs_CrossType(t *testing.T) {
	if errors.Is(ErrInvalidCommand, ErrInvalidFormat) {
		t.Fatalf("errors.Is(ErrInvalidCommand, ErrInvalidFormat) = true, want false")
	}
	if errors.Is(ErrUnauthenticated, ErrUnauthorized) {
		t.Fatalf("errors.Is(ErrUnauthenticated, ErrUnauthorized) = true, want false")
	}
	if errors.Is(ErrStreamIdNotFound, ErrTopicIdNotFound) {
		t.Fatalf("errors.Is(ErrStreamIdNotFound, ErrTopicIdNotFound) = true, want false")
	}
}

func TestIs_DirectCall_AllTypes(t *testing.T) {
	type isChecker interface {
		Is(error) bool
	}

	tests := []struct {
		name string
		err  IggyError
	}{
		{"Error", ErrError},
		{"InvalidConfiguration", ErrInvalidConfiguration},
		{"InvalidCommand", ErrInvalidCommand},
		{"InvalidFormat", ErrInvalidFormat},
		{"FeatureUnavailable", ErrFeatureUnavailable},
		{"InvalidIdentifier", ErrInvalidIdentifier},
		{"InvalidVersion", ErrInvalidVersion},
		{"Disconnected", ErrDisconnected},
		{"CannotEstablishConnection", ErrCannotEstablishConnection},
		{"CannotCreateBaseDirectory", ErrCannotCreateBaseDirectory},
		{"CannotCreateRuntimeDirectory", ErrCannotCreateRuntimeDirectory},
		{"CannotRemoveRuntimeDirectory", ErrCannotRemoveRuntimeDirectory},
		{"CannotCreateStateDirectory", ErrCannotCreateStateDirectory},
		{"StateFileNotFound", ErrStateFileNotFound},
		{"StateFileCorrupted", ErrStateFileCorrupted},
		{"InvalidStateEntryChecksum", ErrInvalidStateEntryChecksum},
		{"CannotOpenDatabase", ErrCannotOpenDatabase},
		{"ResourceNotFound", ErrResourceNotFound},
		{"StaleClient", ErrStaleClient},
		{"TcpError", ErrTcpError},
		{"QuicError", ErrQuicError},
		{"InvalidServerAddress", ErrInvalidServerAddress},
		{"InvalidClientAddress", ErrInvalidClientAddress},
		{"InvalidIpAddress", ErrInvalidIpAddress},
		{"Unauthenticated", ErrUnauthenticated},
		{"Unauthorized", ErrUnauthorized},
		{"InvalidCredentials", ErrInvalidCredentials},
		{"InvalidUsername", ErrInvalidUsername},
		{"InvalidPassword", ErrInvalidPassword},
		{"InvalidUserStatus", ErrInvalidUserStatus},
		{"UserAlreadyExists", ErrUserAlreadyExists},
		{"UserInactive", ErrUserInactive},
		{"CannotDeleteUser", ErrCannotDeleteUser},
		{"CannotChangePermissions", ErrCannotChangePermissions},
		{"InvalidPersonalAccessTokenName", ErrInvalidPersonalAccessTokenName},
		{"PersonalAccessTokenAlreadyExists", ErrPersonalAccessTokenAlreadyExists},
		{"PersonalAccessTokensLimitReached", ErrPersonalAccessTokensLimitReached},
		{"InvalidPersonalAccessToken", ErrInvalidPersonalAccessToken},
		{"PersonalAccessTokenExpired", ErrPersonalAccessTokenExpired},
		{"UsersLimitReached", ErrUsersLimitReached},
		{"NotConnected", ErrNotConnected},
		{"ClientShutdown", ErrClientShutdown},
		{"InvalidTlsDomain", ErrInvalidTlsDomain},
		{"InvalidTlsCertificatePath", ErrInvalidTlsCertificatePath},
		{"InvalidTlsCertificate", ErrInvalidTlsCertificate},
		{"FailedToAddCertificate", ErrFailedToAddCertificate},
		{"InvalidEncryptionKey", ErrInvalidEncryptionKey},
		{"CannotEncryptData", ErrCannotEncryptData},
		{"CannotDecryptData", ErrCannotDecryptData},
		{"InvalidJwtAlgorithm", ErrInvalidJwtAlgorithm},
		{"InvalidJwtSecret", ErrInvalidJwtSecret},
		{"JwtMissing", ErrJwtMissing},
		{"CannotGenerateJwt", ErrCannotGenerateJwt},
		{"AccessTokenMissing", ErrAccessTokenMissing},
		{"InvalidAccessToken", ErrInvalidAccessToken},
		{"InvalidSizeBytes", ErrInvalidSizeBytes},
		{"InvalidUtf8", ErrInvalidUtf8},
		{"InvalidNumberEncoding", ErrInvalidNumberEncoding},
		{"InvalidBooleanValue", ErrInvalidBooleanValue},
		{"InvalidNumberValue", ErrInvalidNumberValue},
		{"ClientNotFound", ErrClientNotFound},
		{"InvalidClientId", ErrInvalidClientId},
		{"ConnectionClosed", ErrConnectionClosed},
		{"CannotParseHeaderKind", ErrCannotParseHeaderKind},
		{"HttpResponseError", ErrHttpResponseError},
		{"InvalidHttpRequest", ErrInvalidHttpRequest},
		{"InvalidJsonResponse", ErrInvalidJsonResponse},
		{"InvalidBytesResponse", ErrInvalidBytesResponse},
		{"EmptyResponse", ErrEmptyResponse},
		{"CannotCreateEndpoint", ErrCannotCreateEndpoint},
		{"CannotParseUrl", ErrCannotParseUrl},
		{"CannotCreateStreamsDirectory", ErrCannotCreateStreamsDirectory},
		{"CannotCreateStreamDirectory", ErrCannotCreateStreamDirectory},
		{"CannotCreateStreamInfo", ErrCannotCreateStreamInfo},
		{"CannotUpdateStreamInfo", ErrCannotUpdateStreamInfo},
		{"CannotOpenStreamInfo", ErrCannotOpenStreamInfo},
		{"CannotReadStreamInfo", ErrCannotReadStreamInfo},
		{"CannotCreateStream", ErrCannotCreateStream},
		{"CannotDeleteStream", ErrCannotDeleteStream},
		{"CannotDeleteStreamDirectory", ErrCannotDeleteStreamDirectory},
		{"StreamIdNotFound", ErrStreamIdNotFound},
		{"StreamNameNotFound", ErrStreamNameNotFound},
		{"StreamIdAlreadyExists", ErrStreamIdAlreadyExists},
		{"StreamNameAlreadyExists", ErrStreamNameAlreadyExists},
		{"InvalidStreamName", ErrInvalidStreamName},
		{"InvalidStreamId", ErrInvalidStreamId},
		{"CannotReadStreams", ErrCannotReadStreams},
		{"InvalidTopicSize", ErrInvalidTopicSize},
		{"CannotCreateTopicsDirectory", ErrCannotCreateTopicsDirectory},
		{"CannotCreateTopicDirectory", ErrCannotCreateTopicDirectory},
		{"CannotCreateTopicInfo", ErrCannotCreateTopicInfo},
		{"CannotUpdateTopicInfo", ErrCannotUpdateTopicInfo},
		{"CannotOpenTopicInfo", ErrCannotOpenTopicInfo},
		{"CannotReadTopicInfo", ErrCannotReadTopicInfo},
		{"CannotCreateTopic", ErrCannotCreateTopic},
		{"CannotDeleteTopic", ErrCannotDeleteTopic},
		{"CannotDeleteTopicDirectory", ErrCannotDeleteTopicDirectory},
		{"CannotPollTopic", ErrCannotPollTopic},
		{"TopicIdNotFound", ErrTopicIdNotFound},
		{"TopicNameNotFound", ErrTopicNameNotFound},
		{"TopicIdAlreadyExists", ErrTopicIdAlreadyExists},
		{"TopicNameAlreadyExists", ErrTopicNameAlreadyExists},
		{"InvalidTopicName", ErrInvalidTopicName},
		{"TooManyPartitions", ErrTooManyPartitions},
		{"InvalidTopicId", ErrInvalidTopicId},
		{"CannotReadTopics", ErrCannotReadTopics},
		{"InvalidReplicationFactor", ErrInvalidReplicationFactor},
		{"CannotCreatePartition", ErrCannotCreatePartition},
		{"CannotCreatePartitionsDirectory", ErrCannotCreatePartitionsDirectory},
		{"CannotCreatePartitionDirectory", ErrCannotCreatePartitionDirectory},
		{"CannotOpenPartitionLogFile", ErrCannotOpenPartitionLogFile},
		{"CannotReadPartitions", ErrCannotReadPartitions},
		{"CannotDeletePartition", ErrCannotDeletePartition},
		{"CannotDeletePartitionDirectory", ErrCannotDeletePartitionDirectory},
		{"PartitionNotFound", ErrPartitionNotFound},
		{"NoPartitions", ErrNoPartitions},
		{"TopicFull", ErrTopicFull},
		{"CannotDeleteConsumerOffsetsDirectory", ErrCannotDeleteConsumerOffsetsDirectory},
		{"CannotDeleteConsumerOffsetFile", ErrCannotDeleteConsumerOffsetFile},
		{"CannotCreateConsumerOffsetsDirectory", ErrCannotCreateConsumerOffsetsDirectory},
		{"CannotReadConsumerOffsets", ErrCannotReadConsumerOffsets},
		{"ConsumerOffsetNotFound", ErrConsumerOffsetNotFound},
		{"SegmentNotFound", ErrSegmentNotFound},
		{"SegmentClosed", ErrSegmentClosed},
		{"InvalidSegmentSize", ErrInvalidSegmentSize},
		{"CannotCreateSegmentLogFile", ErrCannotCreateSegmentLogFile},
		{"CannotCreateSegmentIndexFile", ErrCannotCreateSegmentIndexFile},
		{"CannotCreateSegmentTimeIndexFile", ErrCannotCreateSegmentTimeIndexFile},
		{"CannotSaveMessagesToSegment", ErrCannotSaveMessagesToSegment},
		{"CannotSaveIndexToSegment", ErrCannotSaveIndexToSegment},
		{"CannotSaveTimeIndexToSegment", ErrCannotSaveTimeIndexToSegment},
		{"InvalidMessagesCount", ErrInvalidMessagesCount},
		{"CannotAppendMessage", ErrCannotAppendMessage},
		{"CannotReadMessage", ErrCannotReadMessage},
		{"CannotReadMessageId", ErrCannotReadMessageId},
		{"CannotReadMessageState", ErrCannotReadMessageState},
		{"CannotReadMessageTimestamp", ErrCannotReadMessageTimestamp},
		{"CannotReadHeadersLength", ErrCannotReadHeadersLength},
		{"CannotReadHeadersPayload", ErrCannotReadHeadersPayload},
		{"TooBigUserHeaders", ErrTooBigUserHeaders},
		{"InvalidHeaderKey", ErrInvalidHeaderKey},
		{"InvalidHeaderValue", ErrInvalidHeaderValue},
		{"CannotReadMessageLength", ErrCannotReadMessageLength},
		{"CannotReadMessagePayload", ErrCannotReadMessagePayload},
		{"TooBigMessagePayload", ErrTooBigMessagePayload},
		{"TooManyMessages", ErrTooManyMessages},
		{"EmptyMessagePayload", ErrEmptyMessagePayload},
		{"InvalidMessagePayloadLength", ErrInvalidMessagePayloadLength},
		{"CannotReadMessageChecksum", ErrCannotReadMessageChecksum},
		{"InvalidMessageChecksum", ErrInvalidMessageChecksum},
		{"InvalidKeyValueLength", ErrInvalidKeyValueLength},
		{"CommandLengthError", ErrCommandLengthError},
		{"InvalidSegmentsCount", ErrInvalidSegmentsCount},
		{"NonZeroOffset", ErrNonZeroOffset},
		{"NonZeroTimestamp", ErrNonZeroTimestamp},
		{"MissingIndex", ErrMissingIndex},
		{"InvalidIndexesByteSize", ErrInvalidIndexesByteSize},
		{"InvalidIndexesCount", ErrInvalidIndexesCount},
		{"InvalidMessagesSize", ErrInvalidMessagesSize},
		{"TooSmallMessage", ErrTooSmallMessage},
		{"CannotSendMessagesDueToClientDisconnection", ErrCannotSendMessagesDueToClientDisconnection},
		{"BackgroundSendError", ErrBackgroundSendError},
		{"BackgroundSendTimeout", ErrBackgroundSendTimeout},
		{"BackgroundSendBufferFull", ErrBackgroundSendBufferFull},
		{"BackgroundWorkerDisconnected", ErrBackgroundWorkerDisconnected},
		{"BackgroundSendBufferOverflow", ErrBackgroundSendBufferOverflow},
		{"ProducerSendFailed", ErrProducerSendFailed},
		{"ProducerClosed", ErrProducerClosed},
		{"InvalidOffset", ErrInvalidOffset},
		{"ConsumerGroupIdNotFound", ErrConsumerGroupIdNotFound},
		{"ConsumerGroupIdAlreadyExists", ErrConsumerGroupIdAlreadyExists},
		{"InvalidConsumerGroupId", ErrInvalidConsumerGroupId},
		{"ConsumerGroupNameNotFound", ErrConsumerGroupNameNotFound},
		{"ConsumerGroupNameAlreadyExists", ErrConsumerGroupNameAlreadyExists},
		{"InvalidConsumerGroupName", ErrInvalidConsumerGroupName},
		{"ConsumerGroupMemberNotFound", ErrConsumerGroupMemberNotFound},
		{"CannotCreateConsumerGroupInfo", ErrCannotCreateConsumerGroupInfo},
		{"CannotDeleteConsumerGroupInfo", ErrCannotDeleteConsumerGroupInfo},
		{"MissingBaseOffsetRetainedMessageBatch", ErrMissingBaseOffsetRetainedMessageBatch},
		{"MissingLastOffsetDeltaRetainedMessageBatch", ErrMissingLastOffsetDeltaRetainedMessageBatch},
		{"MissingMaxTimestampRetainedMessageBatch", ErrMissingMaxTimestampRetainedMessageBatch},
		{"MissingLengthRetainedMessageBatch", ErrMissingLengthRetainedMessageBatch},
		{"MissingPayloadRetainedMessageBatch", ErrMissingPayloadRetainedMessageBatch},
		{"CannotReadBatchBaseOffset", ErrCannotReadBatchBaseOffset},
		{"CannotReadBatchLength", ErrCannotReadBatchLength},
		{"CannotReadLastOffsetDelta", ErrCannotReadLastOffsetDelta},
		{"CannotReadMaxTimestamp", ErrCannotReadMaxTimestamp},
		{"CannotReadBatchPayload", ErrCannotReadBatchPayload},
		{"InvalidConnectionString", ErrInvalidConnectionString},
		{"SnapshotFileCompletionFailed", ErrSnapshotFileCompletionFailed},
		{"CannotSerializeResource", ErrCannotSerializeResource},
		{"CannotDeserializeResource", ErrCannotDeserializeResource},
		{"CannotReadFile", ErrCannotReadFile},
		{"CannotReadFileMetadata", ErrCannotReadFileMetadata},
		{"CannotSeekFile", ErrCannotSeekFile},
		{"CannotAppendToFile", ErrCannotAppendToFile},
		{"CannotWriteToFile", ErrCannotWriteToFile},
		{"CannotOverwriteFile", ErrCannotOverwriteFile},
		{"CannotDeleteFile", ErrCannotDeleteFile},
		{"CannotSyncFile", ErrCannotSyncFile},
		{"CannotReadIndexOffset", ErrCannotReadIndexOffset},
		{"CannotReadIndexPosition", ErrCannotReadIndexPosition},
		{"CannotReadIndexTimestamp", ErrCannotReadIndexTimestamp},
	}

	for _, tt := range tests {
		t.Run(tt.name+"/self_match", func(t *testing.T) {
			checker, ok := tt.err.(isChecker)
			if !ok {
				t.Fatalf("%s does not implement Is(error) bool", tt.name)
			}
			if !checker.Is(tt.err) {
				t.Fatalf("%s.Is(self) = false, want true", tt.name)
			}
		})
		t.Run(tt.name+"/cross_type_reject", func(t *testing.T) {
			checker, ok := tt.err.(isChecker)
			if !ok {
				t.Fatalf("%s does not implement Is(error) bool", tt.name)
			}
			other := fmt.Errorf("unrelated error")
			if checker.Is(other) {
				t.Fatalf("%s.Is(unrelated) = true, want false", tt.name)
			}
		})
	}
}

func TestWrappedErrorsIs(t *testing.T) {
	wrapped := fmt.Errorf("context: %w", ErrInvalidCommand)
	if !errors.Is(wrapped, ErrInvalidCommand) {
		t.Fatalf("errors.Is(wrapped, ErrInvalidCommand) = false, want true")
	}
	if errors.Is(wrapped, ErrInvalidFormat) {
		t.Fatalf("errors.Is(wrapped, ErrInvalidFormat) = true for wrong type")
	}
}
