[elasticsearch]  
url = "http://localhost:9200"  
index_pattern = "logs-*"  
poll_interval_secs = 30  
batch_size = 500  
scroll_timeout_secs = 60  
max_docs_per_poll = 5000  
  
[elasticsearch.query]  
json = '''  
{  
  "bool": {  
    "must": [  
      {"range": {"@timestamp": {"gte": "now-1h"}}}  
    ]  
  }  
}  
'''  
  
[iggy]  
stream = "external-logs"  
topic = "imported-logs"  
  
[state]  
file_path = "./elasticsearch_source_state.json"  
timestamp_field = "@timestamp"  
sort_field = "@timestamp"