[package]
name = "iggy-cmd"
version = "0.6.1"
edition = "2021"
authors = ["bartosz.ciesla@gmail.com"]
repository = "https://github.com/iggy-rs/iggy"

[dependencies]
iggy = { path = "../iggy", features = ["iggy-cmd"] }
clap = { version = "4.1.11", features = ["derive"] }
tokio = { version = "1.28.2", features = ["full"] }
async-trait = "0.1.68"
anyhow = "1.0.75"
thiserror = "1.0.48"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17" }
tracing-appender = "0.2.2"
passterm = "2.0.1"

[dev-dependencies]
uuid = { version = "1.3.3", features = ["v4", "fast-rng", "zerocopy"] }
assert_cmd = "2.0.12"
predicates = "3.0.3"
libc = "0.2.147"
serial_test = "2.0.0"
async-dropper = { version = "0.2.3", features = ["tokio"] }

[[bin]]
name = "iggy"
path = "src/main.rs"
