[package]
name = "iggy-cmd"
version = "0.1.0"
edition = "2021"
authors = ["bartosz.ciesla@gmail.com"]
repository = "https://github.com/iggy-rs/iggy"

[dependencies]
iggy = { path = "../iggy" }
clap = { version = "4.1.11", features = ["derive"] }
tokio = { version = "1.28.2", features = ["full"] }
async-trait = "0.1.68"
comfy-table = "7.0.1"
anyhow = "1.0.75"
thiserror = "1.0.48"

[[bin]]
name = "iggy"
path = "src/main.rs"
