# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

@url = http://localhost:8081
@sink_key = stdout
@sink_version = 0
@source_key = random
@source_version = 0

###
GET {{url}}

###
GET {{url}}/health

###
GET {{url}}/sinks

###
GET {{url}}/sinks/{{sink_key}}

###
GET {{url}}/sinks/{{sink_key}}/configs

###
#POST {{url}}/sinks/{{sink_key}}/configs

###
GET {{url}}/sinks/{{sink_key}}/configs/{{sink_version}}

###
GET {{url}}/sinks/{{sink_key}}/configs/active

###
#PUT {{url}}/sinks/{{sink_key}}/configs/active

###
GET {{url}}/sinks/{{sink_key}}/configs/plugin

###
GET {{url}}/sinks/{{sink_key}}/transforms

###
GET {{url}}/sources

###
GET {{url}}/sources/{{source_key}}

###
GET {{url}}/sources/{{source_key}}/configs

###
#POST {{url}}/sources/{{source_key}}/configs

###
GET {{url}}/sources/{{source_key}}/configs/{{source_version}}

###
GET {{url}}/sources/{{source_key}}/configs/active

###
#PUT {{url}}/sources/{{source_key}}/configs/active

###
GET {{url}}/sources/{{source_key}}/configs/plugin

###
GET {{url}}/sources/{{source_key}}/transforms
