[package]
name = "iggy"
version = "0.2.3"
description = "Iggy is the persistent message streaming platform written in Rust, supporting QUIC, TCP and HTTP transport protocols, capable of processing millions of messages per second."
edition = "2021"
license = "MIT"
keywords = ["iggy", "messaging", "streaming"]
categories = ["command-line-utilities", "database", "network-programming"]
homepage = "https://iggy.rs"
documentation = "https://docs.iggy.rs"
repository = "https://github.com/iggy-rs/iggy"
readme = "../README.md"

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.79"
async-dropper = { version = "0.3.1", features = ["tokio", "simple"] }
async-trait = "0.1.77"
base64 = "0.21.7"
byte-unit = { version = "5.1.4", default-features = false, features = [
  "serde",
  "byte",
  "std",
] }
bytes = "1.5.0"
chrono = { version = "0.4.33" }
clap = { version = "4.4.18", features = ["derive"] }
comfy-table = { version = "7.1.0", optional = true }
crc32fast = "1.3.2"
flume = "0.11.0"
humantime = "2.1.0"
keyring = { version = "2.3.2", optional = true }
lazy_static = "1.4.0"
openssl = { version = "0.10.63", features = ["vendored"] }
passterm = { version = "2.0.1", optional = true }
quinn = { version = "0.10.2" }
regex = "1.10.3"
reqwest = { version = "0.11.24", features = ["json"] }
reqwest-middleware = "0.2.4"
reqwest-retry = "0.3.0"
rustls = { version = "0.21.10", features = ["dangerous_configuration"] }
serde = { version = "1.0.196", features = ["derive", "rc"] }
serde_json = "1.0.113"
serde_with = { version = "3.6.0", features = ["base64"] }
strum = { version = "0.26.1", features = ["derive"] }
thiserror = "1.0.56"
tokio = { version = "1.36.0", features = ["full"] }
tokio-native-tls = "0.3.1"
tracing = { version = "0.1.40" }

[build-dependencies]
convert_case = "0.6.0"
rmp-serde = "1.1.2"
serde = { version = "1.0.196", features = ["derive", "rc"] }
serde_derive = "1.0.194"

[features]
default = []
iggy-cli = ["dep:comfy-table", "dep:keyring", "dep:passterm"]
