[package]
name = "tools"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "data-seeder-tool"
path = "src/data-seeder/main.rs"

[dependencies]
iggy = { path = "../iggy" }
anyhow = "1.0.70"
bytes = "1.4.0"
clap = { version = "4.1.11", features = ["derive"] }
rand = "0.8.5"
rcgen = "0.11.1"
rustls = { version = "0.21.1", features = ["dangerous_configuration", "quic"] }
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.16" }
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["full"] }
tokio-rustls = "0.24.0"
