apiVersion: v1
kind: Service
metadata:
  name: {{ include "iggy-server.fullname" . }}
  labels:
    {{- include "iggy-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.server.ports.http }}
      targetPort: http
      protocol: TCP
    - name: quic
      port: {{ .Values.server.ports.quic }}
      targetPort: quic
      protocol: TCP
    - name: tcp
      port: {{ .Values.server.ports.tcp }}
      targetPort: tcp
      protocol: TCP
  selector:
    {{- include "iggy-server.selectorLabels" . | nindent 4 }}
