name: security
on:
  schedule:
    - cron: '0 13 * * *'  # At 13:00 AM UTC, which is 14:00 PM CET

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
