name: Security audit
on:
  schedule:
    - cron: '0 11 * * *'  # At 11:00 AM UTC, which is 12:00 PM CET
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
