name: security
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # At 8:00 AM UTC, which is 9:00 AM CET

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
