# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Cross-SDK BDD Tests

on:
  workflow_call:

jobs:
  bdd-tests:
    name: BDD tests (${{ matrix.sdk }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [rust, python]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target
            foreign/python -> target
          cache-on-failure: true
          key: bdd-${{ matrix.sdk }}

      - name: Run BDD tests for ${{ matrix.sdk }}
        run: ./scripts/run-bdd-tests.sh ${{ matrix.sdk }}

      - name: Clean up Docker resources
        if: always()
        run: ./scripts/run-bdd-tests.sh clean