name: CI
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read
  security-events: write

jobs:
  detect:
    name: Detect changes
    uses: ./.github/workflows/_detect.yml

  test:
    name: Test ${{ matrix.component }}/${{ matrix.task }}
    needs: detect
    if: ${{ fromJson(needs.detect.outputs.matrix).include[0].component != 'noop' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.detect.outputs.matrix) }}
    uses: ./.github/workflows/_test.yml
    with:
      component: ${{ matrix.component }}
      task: ${{ matrix.task }}

  bdd:
    name: BDD Tests
    needs: test
    if: |
      always() && 
      needs.test.result != 'cancelled' &&
      (github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'run-bdd'))
    uses: ./.github/workflows/_bdd.yml

  security:
    name: Security Scan
    needs: detect
    if: always()
    uses: ./.github/workflows/_security.yml
    with:
      create_issues: false

  status:
    name: CI Status
    runs-on: ubuntu-latest
    needs: [detect, test, bdd, security]
    if: always()
    steps:
      - name: Check status
        run: |
          echo "## CI Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Detect | ${{ needs.detect.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Test | ${{ needs.test.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| BDD | ${{ needs.bdd.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Security | ${{ needs.security.result }} |" >> $GITHUB_STEP_SUMMARY
          
          # Fail if any required job failed
          if [ "${{ needs.test.result }}" = "failure" ]; then
            echo "Tests failed"
            exit 1
          fi
          
          # For PRs, BDD is optional
          if [ "${{ github.event_name }}" = "push" ] && [ "${{ needs.bdd.result }}" = "failure" ]; then
            echo "BDD tests failed on master"
            exit 1
          fi
          
      - name: Comment on PR
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `## ❌ CI Failed
            
            Please check the [workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.
            
            | Check | Status |
            |-------|--------|
            | Tests | ${{ needs.test.result }} |
            | BDD | ${{ needs.bdd.result }} |
            | Security | ${{ needs.security.result }} |`;
            
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: comment
            });