name: performance
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run_benchmarks:
    runs-on: performance
    env:
      IGGY_CI_BUILD: true
    steps:

      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
        with:
          key: "performance"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify working directory
        run: |
          pwd
          ls -la

      - name: Run predefined benchmarks
        timeout-minutes: 60
        run: ./scripts/performance/run-standard-performance-suite.sh --identifier iggy-ci

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: performance_results
          path: performance_results*
