name: post_release
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["release"]
    types:
      - completed

jobs:
  post_release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
        with:
          key: "v2"

      - name: Build binary
        run: cargo build

      - uses: addnab/docker-run-action@v3
        name: Spin up Docker Container
        with:
          image: iggyrs/iggy
          options: -d -p 8090:8090 --name iggy_container

      - name: Test Benchmark - Send
        timeout-minutes: 1
        run: |
          ./target/debug/iggy-bench send --message-batches 100 --messages-per-batch 100 tcp --server-address 127.0.0.1:8090

      - name: Test Benchmark - Poll
        timeout-minutes: 1
        run: |
          ./target/debug/iggy-bench poll --message-batches 100 --messages-per-batch 100 tcp --server-address 127.0.0.1:8090

      - name: Test Benchmark - Send and Poll
        timeout-minutes: 1
        run: |
          ./target/debug/iggy-bench send-and-poll --message-batches 100 --messages-per-batch 100 tcp --server-address 127.0.0.1:8090

      - name: Test CLI - topic creation
        timeout-minutes: 1
        run: |
          IGGY_USERNAME=iggy IGGY_PASSWORD=iggy ./target/debug/iggy stream create test-stream

      - name: Clean up
        run: docker rm -f iggy_container

  finalize_post_release:
    runs-on: ubuntu-latest
    needs: [post_release]
    if: always()
    steps:
      - uses: actions/checkout@v4

      - name: Everything is fine
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0

      - name: Something went wrong
        if: ${{ contains(needs.*.result, 'failure') && github.event_name == 'workflow_run' }}
        uses: JasonEtco/create-an-issue@v2.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_BOT_CONTEXT_STRING: "post release docker container test"
        with:
          filename: .github/BOT_ISSUE_TEMPLATE.md
