name: sanity
on:
  workflow_dispatch:
  workflow_call:

jobs:
  check:
    name: cargo check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings

  sort:
    name: cargo sort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-sort
      - uses: actions-rs/cargo@v1
        with:
          command: sort
          args: --check --workspace

  doctest:
    name: cargo test docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc

  unused_dependencies:
    name: cargo machete
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-machete
      - uses: actions-rs/cargo@v1
        with:
          command: machete

  check-commit-message:
    name: commit messages
    runs-on: ubuntu-latest
    # This action isn't working with workflow_dispatch, skip it
    if: github.event_name != 'workflow_dispatch'
    steps:
      - name: Check subject line length
        uses: gsactions/commit-message-checker@v2
        with:
          excludeDescription: "false" # exclude description body of a pull request
          excludeTitle: "false" # exclude the title of a pull request
          checkAllCommitMessages: "false" # checks all commits associated with the pull request
          accessToken: ${{ secrets.GITHUB_TOKEN }} # needed only when checkAllCommitMessages is true
          pattern: '^.{0,80}(\n.*)*$'
          error: "Subject of all commits in the PR and PR body/title has to be shorter than 80 characters."
