name: sanity
on:
  workflow_dispatch:
  workflow_call:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: clechasseur/rs-cargo@v2
        with:
          command: check
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup component add rustfmt
      - uses: clechasseur/rs-cargo@v2
        with:
          command: fmt
          args: --all -- --check
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: clechasseur/rs-cargo@v2
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings

  sort:
    name: Sort dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cargo-sort
      - run: cargo sort --check --workspace

  doctest:
    name: Test documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --doc

  unused_dependencies:
    name: Unused dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bnjbvr/cargo-machete@v0.7.0

  check-commit-message:
    name: Validate commit messages
    runs-on: ubuntu-latest
    # This action isn't working with workflow_dispatch, skip it
    if: github.event_name != 'workflow_dispatch'
    steps:
      - name: Check subject line length
        uses: gsactions/commit-message-checker@v2
        with:
          excludeDescription: "false" # exclude description body of a pull request
          excludeTitle: "false" # exclude the title of a pull request
          checkAllCommitMessages: "false" # checks all commits associated with the pull request
          accessToken: ${{ secrets.GITHUB_TOKEN }} # needed only when checkAllCommitMessages is true
          pattern: '^.{0,80}(\n.*)*$'
          error: "Subject of all commits in the PR and PR body/title has to be shorter than 80 characters."
# Uncomment this when we have a proper release - 1.0.0
#   semver-checks:
#     name: SemVer SDK
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: obi1kenobi/cargo-semver-checks-action@v2
#         with:
#           package: iggy
