# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: sanity
on:
  workflow_dispatch:
  workflow_call:

jobs:
  check:
    name: cargo check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings

  sort:
    name: cargo sort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-sort
      - uses: actions-rs/cargo@v1
        with:
          command: sort
          args: --check --workspace

  doctest:
    name: cargo test docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc

  unused_dependencies:
    name: cargo machete
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-machete
      - uses: actions-rs/cargo@v1
        with:
          command: machete
          args: --with-metadata

  check-commit-message:
    name: commit messages
    runs-on: ubuntu-latest
    # This action isn't working with workflow_dispatch, skip it
    if: github.event_name != 'workflow_dispatch'
    steps:
      - name: Check subject line length
        uses: gsactions/commit-message-checker@v2
        with:
          excludeDescription: "false" # exclude description body of a pull request
          excludeTitle: "false" # exclude the title of a pull request
          checkAllCommitMessages: "false" # checks all commits associated with the pull request
          accessToken: ${{ secrets.GITHUB_TOKEN }} # needed only when checkAllCommitMessages is true
          pattern: '^.{0,80}(\n.*)*$'
          error: "Subject of all commits in the PR and PR body/title has to be shorter than 80 characters."
  ci-check-licenses:
    name: license headers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pull addlicense Docker image
        run: docker pull ghcr.io/google/addlicense:latest

      - name: Check license headers
        run: docker run --rm -v ${{ github.workspace }}:/src -w /src ghcr.io/google/addlicense:latest -check -f ASF_LICENSE.txt .
