name: test_pr
on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged

  test:
    needs: if_merged
    uses: ./.github/workflows/test_pr.yml
